### ISSUE TITLE
Full brightness setting @start

### ISSUE THREAD

**Issue by x4080** [syscl/XPS9350-macOS#106]
Hi, @syscl 

Do you have this problem ? It seems happened after updating 10.3.4 
So when boot, the brightness is 100% always, and I have to lower it down manually, already tried using the newest clover but still not working, I think it works fine before updating

**Comment by furrybanana** [comment]
Hi,
this change already happened mid March. So far it seems to be the 'normal' condition now. Same as Wifi-sleep issues since March.

**Comment by x4080** [comment]
Thanks @furrybanana 

I thought that my setting is broken :)

**Comment by squash-** [comment]
@x4080 @furrybanana make sure you have EmuVariableUefi driver installed.

You also need to delete any nvram variables from OS X that are in the hardware nvram.

There is a brightness value stuck in hardware nvram that keeps loading at boot up and is what is making brightness be at max every boot.

Here's how to do it:

In clover start the UEFI shell.

Then type FS0:
and then cd into the EFI folder.

run dmpstore -all -b -s dmpvars.txt

look for a GUID that has fakesmc variables in it. WRITE DOWN THIS GUID.

then run dmpstore -d -guid <INSERT GUID HERE> to delete all of the associated OS X nvram variables under that GUID.

Boot back into OS X, delete nvram.plist from EFI partition, set brightness, reboot, and enjoy consistent brightness.

**Comment by x4080** [comment]
@squash, thanks for the tip sorry for late reply, I'll try it

**Comment by squash** [comment]
Removing myself from this thread as I was tagged on accident
