### ISSUE TITLE
Activity Monitor Power Tab

### ISSUE THREAD

**Issue by mingiryu** [syscl/XPS9350-macOS#109]
The activity monitor crashes when trying to view the power tab. Other tabs like resource and network works fine. However, once I open the power tab, it crashes and I can no longer access the activity monitor as it crashes instantly as it opens.

Spec: 9350 128GB-SATA DW1830 macOS-10.12.5

**Comment by mukulhase** [comment]
Yeah, it's happening for me too

**Comment by furrybanana** [comment]
Just want to confirm: I am having the same issue.

**Comment by ZombieTheBest** [comment]
Delete the Activity Monitor plist file. Then open Activity Monitor again and block that file. It will still crash if you click the energy tab, but it will reopen without need to delete the plist file again. Thanks @bozma88 for this :)
