### ISSUE TITLE
Difficulty booting from USB

### ISSUE THREAD

**Issue by markymmp** [syscl/XPS9350-macOS#111]
Hey guys i'm new to hackintoshing so go easy please ;-) I'm having difficulty booting form USB.. I've followed the instructions by creating a vanilla install disc and used multibeast to install the Uefi boot mode . when i reboot and press F4 it says boot options press F12 so i press it and boot fro USB and replays unable to boot from disc. So i try the legacy boot menu version from Multibeast and it boots into a menu  which i can't select any OS to boot from... Could someone give me assistance of what direction to head please.. Dell is a xps 13 9350 2016 with a 512 ssd 16gb mem so an idea mini powerhouse.. hope you can help..
Regards 

Mark.

**Comment by mingiryu** [comment]
You need to install clover to the usb drive after creating the macOS bootable usb. https://sourceforge.net/projects/cloverefiboot/
In the bios, all you need to change from default is disable secure boot and using AHCI.

**Comment by markymmp** [comment]
great i will try that next.

**Comment by markymmp** [comment]
darn it says "boot0af : error

**Comment by markymmp** [comment]
will try a different USB stick

**Comment by markymmp** [comment]
Hmmmm new stick same error.. very strange... its a 2016 9350 does that make any difference?

**Comment by mingiryu** [comment]
@markymmp Most people here use 2016 9350. Did you follow these steps?

Install Clover with UEFI only and UEFI64Drivers to the installation disk just created.
Replace the original CLOVER folder with the one under my Git/XPS9350-macOS/CLOVER.

And did you create the vanilla usb through the terminal?

**Comment by markymmp** [comment]
Ok cool so at least i know it can be done.. :-) it's just me i guess.. Ok so the only thing I've done different is install the installer / vanilla usb is via Macdaddies Disc installer app... i followed the rest as per instructions... i will try to create it through terminal.. really appreciate the help... :-)

**Comment by furrybanana** [comment]
@markymmp try using this step by step

https://github.com/syscl/XPS9350-macOS/issues/62#issuecomment-280959860

**Comment by markymmp** [comment]
Hmmmm. i must be missing something. Ive tried all methods . I've tried installing sierra via terminal and  via Unibeast adding the boot loaders  and copying the relevant clover folder across within the EFI folder... I must be missing something.

**Comment by markymmp** [comment]
i'm wondering if i can find an alternate boot loader to atlases prove I'm not going mad.. i had everything i thought i needed to get it to boot to USB.. I can get something if i go to legacy boot loader ... a grey screen with tiny text but it doesn't give me a view or option to boot from the mac OSX app/ install.. 
I wondered if copying the files to the c drive and trying it that way may do it? or the restore partition maybe..?

**Comment by mingiryu** [comment]
@markyummp Try this guide https://www.tonymacx86.com/threads/guide-dell-xps-13-9360-on-macos-sierra-10-12-x-lts-long-term-support-guide.213141/

**Comment by markymmp** [comment]
I think I'm loosing something somewhere as all of the instructions seem straightforward here ish. And after copying all the relevant files or using the create boot disk I see error loading OS or can't find boot disk or the errors posted above. If you say it is easy and all the steps I'm taking are not working then I gues it's a lost cause on me as I'm completely missing whether I'm using the right programs to create the right uefi boot. Does that make sense?

**Comment by pomarec** [comment]
@markymmp I have the same config and the same problem, you are not alone in you sadness ;)

**Comment by markymmp** [comment]
This helped me a lot and now i'm able to boot to the UEFI from the USB... not many guide tell you to create a dual partition the UEFI partition formatted in Fat 32 and the OS partition in OSX Journaled.. That worked... Research got me to this point along with the awesome help from sites like this... Taken me 3 weeks to get to this point and i'm understanding more each day.. 
https://www.tonymacx86.com/threads/guide-booting-the-os-x-installer-on-laptops-with-clover.148093/

**Comment by markymmp** [comment]
Thanks for all of the above help. I have done it :-) ... Research and patience. I just need to get sound and wifi running now... But Sierra looks stunning and the touch screen works fantastic.
