### ISSUE TITLE
dw1820无法开启wifi

### ISSUE THREAD

**Issue by helaobibi** [syscl/XPS9350-macOS#112]
先感谢作者，我是xps13 9350 装完10.12.5一切正常，除了wifi无法启动，请问只能更换网卡嘛？有没有其他的方法 ？

**Comment by furrybanana** [comment]
不支持dw1820
最好的解决方案是dw1560
请使用英文。 对不起翻译不好意思

**Comment by helaobibi** [comment]
thank you,my english is too bad,sorry

**Comment by flipphos** [comment]
换卡。换成1560或者1830

**Comment by syscl** [comment]
请更换成DW1560或者DW1830.

谢谢

syscl
