### ISSUE TITLE
Background noise when using headphone

### ISSUE THREAD

**Issue by jerryzj** [syscl/XPS9350-macOS#116]
Hi~ @syscl 

* 中文版
當我使用耳機的時候總是會聽到有背景雜音
我不太確定這是硬體還是軟體的問題
不知道您是否有這問題呢？

    麻煩您解答了 謝謝

    Jerry
* English version
When I using the headphone, I always hear some strange noise
I am not sure it is a hardware or software problem.
Is there anybody have the same problem like me?

    Thanks,
    Jerry

**Comment by mukulhase** [comment]
Yeah, I'm facing the same issue.

**Comment by syscl** [comment]
Hi, seems like all XPS 13 9350 has this issue even under Windows. I don't know why. 

If you are still under warranty, please contact Dell ASAP. Thanks!

syscl

**Comment by jerryzj** [comment]
@syscl Thanks for your reply, I'll contact them soon.
