### ISSUE TITLE
Power plug/unplug freeze

### ISSUE THREAD

**Issue by louwe** [syscl/XPS9350-macOS#117]
For the most part, everything works very well (even the touchscreen) with a couple exceptions that I suspect are related to each other. Thanks for the hard work that goes into making this Clover package.

Whenever I plug/unplug the power cable, OS X Sierra immediately freezes. It doesn't matter if I go from battery to charger or charger to battery; it will immediately freeze both ways.
The other freezing issue that I feel might be related is freeze when I attempt to adjust screen brightness. However, I consider this fairly low priority. Power plug/unplug is much higher priority as it no longer allows me to roam around.

My H/W (as shown by CPU-Z):
Dell XPS 13 9350 QHD+ (touchscreen)
Motherboard: Dell 09JHRY A00
Skylake-U Rev 09
Skylake-Y PCH Rev 21
CPU: Intel Core i7 6560U 2.2 GHz
GPU: Intel Iris Graphics 540
2x 8 GB DDR3
512 GB NVMe

Hope that extra bit helps.
Anyone else here experiencing the power plug/unplug freezing problem that I am experiencing?

Thanks,
~Ed

**Comment by MultiLagio** [comment]
I had this issue originally. The issue was that the script was in a folder with a space (Ex. ~/Documents/Hackintosh Stuff") I just moved it out of the "Hackintosh Stuff" folder and moved it into a different folder without a space.

It might be a different issue from mine but it's worth a try, right?

**Comment by louwe** [comment]
I don't really remember how I ran the script originally. I'll check it tonight.

**Comment by flipphos** [comment]
I am having the same 9350 as yours and I never have this problem. Especially this week, I unplug and plug the power plug several times a day and never had this issue.
I have updated the bios to the latest.

**Comment by louwe** [comment]
That's strange. Could you perhaps list very briefly your install steps?

**Comment by govindmaheshwari2** [comment]
> That's strange. I've also updated the BIOS to the latest from Dell support site.
> 
> Could you perhaps list very briefly your install steps?
> 
> UPDATE:
> I don't know what I did wrong in the beginning.
> But I reran the deploy script; power plug/unplug AND even adjusting screen brightness also no longer freeze the system.
> 
> Thanks all for the replies!!!

hey,
I have the same issue of charger and screen brightness key. please help me in fixing this issue.
I complete don't know how to re-run the script and all.
Please help me solving this issue.
Thank you in Advance.
