### ISSUE TITLE
No bluetooth or wifi on broadcom install 

### ISSUE THREAD

**Issue by markymmp** [syscl/XPS9350-macOS#118]
Did the swap and although the hardware tests say its ok i am unable to switch on wifi.. this is a fresh build and even from the disk util screen wifi is not showing up on the top right task bar by the battery . i'm assuming I've either not installed it right or it's faulty or i've not installed something from the usb drive..

**Comment by jerryzj** [comment]
If you installed DW1830 module, WiFi will work perfectly without any modification(so called OOB).

**Comment by se1ya** [comment]
if u have the DW1820 or DW1820A like me. the wifi isnt work. i dont want to order a 1830 for testing. so i use the Edimax EW-7811UN to test the system. and after install the driver from manufacture, the wifi is working fine with this stick

**Comment by markymmp** [comment]
Ok I am using the 1520 card as recommended I will try a number of reloads to sort it. Slowly getting there and it's a great project :-)

**Comment by markymmp** [comment]
Sorry meant 1560

**Comment by markymmp** [comment]
ok so it would appear i have a faulty dw1560 card so i have ordered the 1830... Anyone have any tips on installing the new card better than i did with the 1560 ...

**Comment by vaites** [comment]
I had some issues installing my DW1830. Use this checklist:

- Check if the card is enabled in BIOS (Wireless section, both wireless and bluetooth)
- Check if the card is enabled through Fn+PrintScreen? (use builting diagnose tool pressing F12 at boot to check)
- Remove all detected network devices in control panel (click _Yes_ on the dialog), run `./Deploy.sh` and reboot
- Add the network device again

To enable device using Fn+PrintScreen I used a live Linux (Ubuntu Linux), that used to check if wireless and bluetooth are detected and worked well.

**Comment by markymmp** [comment]
My 1830 works intermittently and my routers DHCP pool alternates between IP V6 and 4 .. probs appear to happen on V6 ..

**Comment by markymmp** [comment]
Thanks for the reply though..

**Comment by markymmp** [comment]
It was the DW1560
