### ISSUE TITLE
deploy.sh stuck at VoodooPS2

### ISSUE THREAD

**Issue by se1ya** [syscl/XPS9350-macOS#119]
at first, fantastic project, the os runs very well in dualboot. THX syscl

deploy.sh stuck at Install VoodooPS2Controller. if i install with deploy.sh -d it runs well.
but i dont know the install is correct finished. some functions of the trackpad dont run. cant swipe two fingers between the pages in safari
is the function not supported or is the kext running wrong. 
maybe a manually installation can fix it? 

thanks for help

**Comment by aleuts** [comment]
The same thing happened to me, i managed to find a screenshot of the next package to be installed after VoodooPS2Controller and realised it was the WiFi stuff... Then realised i didnt have the required WiFi Card DW1830. I am still using the standard WiFi so i deleted all references to the WiFi etc. and it installed fine minus Wifi!

**Comment by mingiryu** [comment]
@se1ya I have DW1560 and I had the installation stuck at VoodooPS2Controller as well. 
I pressed "enter" about 4 times and the installation resumed. The swipe function works for me.

**Comment by se1ya** [comment]
i have the iris version of the xps with the 1820A and its not working too. so it was the WIFI skipping. 4x enter end it finished the installation without the -d 

thank u guys / and great project

**Comment by mingiryu** [comment]
@se1ya I didn't have the installation issue when I had DW1830. I'm not sure about the swipe gestures
, but everything except the wifi after sleep worked. If you happen to own both DW1830 and DW1560, you can run the script with DW1830 then swap to DW1560 and apply the fix for DW1560.

**Comment by se1ya** [comment]
can be closed (problem solved)
----
newest deploy.sh fixed the problem
