### ISSUE TITLE
No Sound output or Wireless connection.

### ISSUE THREAD

**Issue by markymmp** [syscl/XPS9350-macOS#120]
So i finally have managed to get my Hackintosh booting and running ,all except a few bits but thanks to this project for getting me this far. The screen looks stunning and its a fast little machine.
So a couple of things that I'm having a challenge with firstly i have no Audio and i have tried a few different kexts to sort it to no success.. Secondly no wifi or bluetooth (Using DW1560 card too ) so i've ordered an 1830 card as recommended in the forums.. I'm using ethernet via usb and that works fine for the moment until the new card arrives.. 

So first things first Audio (Says no Output or Input devices) i'm guessing there is a way to sort this and appreciate any help or advice..

**Comment by mingiryu** [comment]
#82 Look into this for DW1560.  Personally, I used clover configurator to edit the config file.
![screen shot 2017-07-16 at 3 13 57 pm](https://user-images.githubusercontent.com/12177666/28250964-816b9082-6a39-11e7-8e95-74a5249cd1cd.png)

**Comment by markymmp** [comment]
what did you edit to get it to work please?

**Comment by markymmp** [comment]
sorry should of read the article.. doing it now
Thankyou.

**Comment by markymmp** [comment]
ok so i entered it exactly on the screen above and following the post #82 saved it unmounted the EFI and rebooted and it's still not showing up on the task bar at the top or in network.. :-(

**Comment by markymmp** [comment]
Sorted thank you

**Comment by louwe** [comment]
OP probably should close this issue considering #82 has already covered this issue.
