### ISSUE TITLE
Function keys F1 - F12 have stopped working. 

### ISSUE THREAD

**Issue by markymmp** [syscl/XPS9350-macOS#125]
A weird one as I had them all working controlling volume and brightness and keyboard brightness perfectly. I left the Hacbook on yesterday all day to test for crashes .. wifi was twitchy but useable but when I went to brighten the screen it acted like how hot cornrers behave and now I have no control.  F12 stops the mouse pad but works again when I press it again. Any ideas.?

**Comment by markymmp** [comment]
Hello ?

**Comment by markymmp** [comment]
Resolved it... copied the clover folder from my install drive onto my Efi partition and re patched it..

**Comment by syscl** [comment]
Hi, please use the latest deploy.sh then report.

Thank you,
syscl

**Comment by markymmp** [comment]
ok .. I did fix the issue by copying the refi files from the USB i created to build the Hackintosh.. Testing a twitchy wifi prob at the mo

**Comment by markymmp** [comment]
ok i've deployed it and so far so good.. wifi has improved (using DW1830) as i've had to sort out my home router and fixed the ip address .. I've done multiple resets and standbys and all looks good at the moment

**Comment by syscl** [comment]
@markymmp Please wait a few seconds, I will upload the latest VoodooPS2 that supports macOS High Sierra. Try it then report.

Thank you,
syscl

**Comment by syscl** [comment]
Done, please try the latest deploy.sh and VoodooPS2. It should give you the correct trackpad..

syscl

**Comment by markymmp** [comment]
ok Deployed will report back... Fantastic work ... thank you

**Comment by markymmp** [comment]
Ok seems stable and noticed the boot grafix have speeded up the twitch. Keyboard is fine no more probs with the F Keys.

**Comment by syscl** [comment]
@markymmp Nice, can you close this issue if solved?

thank you,syscl
