### ISSUE TITLE
Battery Life

### ISSUE THREAD

**Issue by MemoTRDE** [syscl/XPS9350-macOS#126]
Hello, 
can somebody tell me how the battery life is? 
I can get up to 10 hours of use on windows, I hope it's comparable in MacOs.
Also is the DW1820A supported now? 

Thanks for any answers :)

Best Regards
Memo

**Comment by syscl** [comment]
Hi, DW1820A is unsupported, please switch to DW1560 or DW1830. 

Battery life is about 7-8 hours with Iris 540, 1 hours longer with non-Iris version. If you use 1920x1080p version of this laptop, it will last about 13-15 hours(I guess).

syscl
