### ISSUE TITLE
10.12.6 发现问题

### ISSUE THREAD

**Issue by bynce** [syscl/XPS9350-macOS#127]
继续测试：发现三次 突然卡顿只能重启解决。
系统：10.12.6  以下不工作：
1.F1-F12快捷键 。按快捷键几率性卡死（冻屏）。
2.开机 亮度和声音最大。 开机后必须调节。
3.OsxAptioFix2Drv-64.efi 无法工作。 现在使用OsxAptioFixDrv-64.efi
4.默认usb 不工作。 需要加入：USB_injector.kext

**Comment by syscl** [comment]
@bynce 请尝试最新的deploy.sh并反馈，谢谢！

---
@bynce Please try the latest deploy then report, thank you!

syscl

**Comment by bynce** [comment]
我重新安装几遍都是会 卡顿 更甚 死机 。 重新复位bios 暂时还没发现死机 卡顿的现象。
