### ISSUE TITLE
cant find clover revision 4218

### ISSUE THREAD

**Issue by se1ya** [syscl/XPS9350-macOS#129]
i want to update clover to the newest version **r4218**. But the only version i found was **r4128** [here](https://sourceforge.net/projects/cloverefiboot/). is it twisted numbers or how can i find the version **r4218**?

BTW: is it possible to open a gitter chat for this project? some problems can handle without open an issue here. :) like my

**Comment by xaek** [comment]
it's a typo...

**Comment by se1ya** [comment]
Okay thank you for info. 
are u updated the 4128? 
my clover ui is very slow, sometimes it need three times to accept enter-button

**Comment by xaek** [comment]
No problem with clover 4128 boot gui.
Try deploying latest version of this repo.

**Comment by syscl** [comment]
@xaek Thank you,

syscl
