### ISSUE TITLE
Wifi performance issues using Bluetooth audio at the same time

### ISSUE THREAD

**Issue by vaites** [syscl/XPS9350-macOS#130]
I connected today my Bluetooth headset and wireless performace drops drastically. When I disconnect the device, wireless works well at the moment. I have connected a Magic Trackpad and did not suffered any performace issue. 

Is anyone having this problem?

**Comment by flipphos** [comment]
Could you try to use the wifi at 5 G when using BT to see if it helps?

**Comment by vaites** [comment]
Thanks @flipphos, I tested it with a 5ghz wifi and works well.

**Comment by louwe** [comment]
You should close the issue if it is resolved.

**Comment by vaites** [comment]
The problem remains for 2.4ghz wifi, but seems to be an Apple issue: https://apple.stackexchange.com/questions/153009/bluetooth-and-wifi-interfering-with-one-another-since-yosemite

They suggest to remove _Bluetooth PAN_ network device...
