### ISSUE TITLE
WiFi detected but cannot be enabled

### ISSUE THREAD

**Issue by BJoe1** [syscl/XPS9350-macOS#131]
Is there a way to debug the issue? WiFi is being detected by the OS in the network preferences and I can remove it and add it back, however I whenever I press the "enable WiFi" button it immediately reverts back and it never turns on. Where should I look to see what causes the issue? I'm using the latest deploy. In Windows the broadcom card in this Dell is identified as 14e4:43a3.

**Comment by se1ya** [comment]
wich wifi card are you have installed on your machine?

**Comment by louwe** [comment]
If you have a 9350 and you did not replace the WiFi card, you have the stock DW1820A and it is not supported. Get the DW1560 on eBay.

**Comment by BJoe1** [comment]
Yep. It is stock 9350 and I wasn't aware that you could replace it (thought it was soldered onto the motherboard like most everything else). Thanks for the info, I've been looking at various XPS guides and never saw that (stock) DW1820A was explicitly not supported.
