### ISSUE TITLE
Intermittent Bluetooth on the DW 1830 card

### ISSUE THREAD

**Issue by markymmp** [syscl/XPS9350-macOS#134]
Hi guys firstly thanks for this great site . It's help me create a stable Hackbook Ultrabook for DJing. I wondered if anyone has had intermittent bluetooth problems with the DW1830 card.. it keeps disconnecting from my apple Mouse and AirPods audio is not very stable. I've given up with hand off and facetime and hand off as i can't get iChat stuff to work.. Yup i have tried the idiots guide 5 times.. 

so just bluetooth .. and i'm happy..

**Comment by vaites** [comment]
Are you using Wifi on 2.4ghz at the same time? Try disabling wireless, because maybe is the same problem described in #130

**Comment by markymmp** [comment]
tried that ... suspect its a dodgy antenna connection.. will investigate..

**Comment by markymmp** [comment]
Ok i can close this now it's an antenna thing as and the field strength is better on the left side.. my Magic mouse works better on the Left and yup i am using the 5G wifi range..
