### ISSUE TITLE
I broke Bluetooth.... and I don't know how.

### ISSUE THREAD

**Issue by ZombieTheBest** [syscl/XPS9350-macOS#138]
Hello. I feel like an idiot right now, but I need help. Using BT AirPods I was experiencing low bitrate audio quality during Siri and Calls (Discord, Telegram Calls etc...). So, low quality when mic was powered on. 
Searching for a solution I found this: https://www.reddit.com/r/apple/comments/5rfdj6/pro_tip_significantly_improve_bluetooth_audio/

I followed the tutorial, did a reboot, and this was the result: 
<img width="257" alt="schermata 2017-08-19 alle 14 45 45" src="https://user-images.githubusercontent.com/22716366/29486719-1bf7e196-84ed-11e7-83fb-00593d08c441.png">

"Bluetooth not available", that's what is written there.
I cannot see the bluetooth under settings too: 
<img width="748" alt="schermata 2017-08-19 alle 14 46 25" src="https://user-images.githubusercontent.com/22716366/29486722-3222f3f2-84ed-11e7-8f98-8ae5e0baf108.png">

I reverted back the changes and deleted all bluetooth.plist files under Library, but with no success. I tried to run Deploy again but no result.

Help please, I don't know what to do D:

**Comment by ZombieTheBest** [comment]
Solved. Sleep fixed bluetooth issue. I feel like an idiot twice.

**Comment by syscl** [comment]
Not a problem, thank you for your persistency and valuable feedback. Don't feel idiot, because we figure out solutions when we make mistakes.

syscl
