### ISSUE TITLE
when I use timemachine to restore my imac's backup , the panel of trackpad change to the bluetooth board, how I can change back?

### ISSUE THREAD

**Issue by sheshui** [syscl/XPS9350-macOS#140]
<img width="668" alt="wx20170822-154210 2x" src="https://user-images.githubusercontent.com/15264018/29554115-8958c6c8-8750-11e7-83c0-2ff060f00230.png">
:( who can help me!

**Comment by ZombieTheBest** [comment]
Is trackpad working? Try to run Deploy again
