### ISSUE TITLE
DW1830 & DW1560 Slow Wi-Fi After Sleep + BT issue FIX [CONFIRMED WORKING - Already included in Deploy]

### ISSUE THREAD

**Issue by ZombieTheBest** [syscl/XPS9350-macOS#145]
**This fix works for both DW1560 and DW1830 for WiFi and BT issue. It is already included in last deploy, but in case Deploy didn't fixed the issue try to do it manually by following this guide! Also check you have all the correct patches for your WiFi hw in config.plist (DW 1560 needs fcvo patch!), and all the necessary kexts**

Hello! I think I've finally solved slow WiFi issue after sleep and WiFi+BT problem on DW1830, thanks to RehabMan on tonymac: https://www.tonymacx86.com/threads/dell-dw1560-dw1830-wifi-bt-issue-on-xps9350.230858/

As you can see from the thread up here I've asked for help solving this issue. On that post you can see screenshots of High Router Ping after sleep, but I got other problems too, like BT disconnecting and WiFi disconnecting while using BT. Now I think i've finally solved it by doing what RehabMan told me, as you can see from the screenshot below (first ping before sleep, and the second one after sleep, both with BT connected and playing music. Speedtest is fine too):
<img width="485" alt="schermata 2017-09-03 alle 22 53 55" src="https://user-images.githubusercontent.com/22716366/30006547-cd8a4f48-90fa-11e7-8854-3e54b9ede251.png">

**How did I solved it?** Not sure about what solved the issue, but i will tell you what I've done:

1. Moved all kexts from Clover to S/L/E (didn't helped but Rehabman adviced me)
2. Removed 5Ghz/fcvo patches from my config.plist (not needed)
3. Corrected some values in config.plist (refer to the post above, or see my config.plist in attachments)
4. Disabled "Wake WiFi for Network Access" under SysPref->Energy->Power (already done, this may be one of the causes tho).

**5. Corrected USB Configuration (i think THIS solved the issue)**, please confirm by trying to do this before anything else.

My UsbConnector values were wrong, internal devices (touchscreen, camera and BLUETOOTH) had 0x03 (USB 3.0) UsbConnector value. They have to be set at 0xFF (Internal). I think that this solved the issue. So, you need to edit Clover/ACPI/patched/SSDT-XHC.aml according to your USB Configuration. Here's how to do this:

1. Make a backup of SSDT-XHC.aml
2. Download iasl, place iasl and SSDT-XHC.aml in the same folder and run ./iasl -da -dl SSDT-XHC.aml
3. Download MaciASL and open the extracted dsl file.
4. Download  IORegistryExplorer and open it. 
5. Search for XHC Controller
<img width="372" alt="schermata 2017-09-03 alle 23 05 23" src="https://user-images.githubusercontent.com/22716366/30006614-68aaff08-90fc-11e7-936a-38dff3cb9026.png">

As you can see in my case HS01 and HS02 are my laptop USB ports (nothing connected, but if you connect a pendrive it will show up there). HS03 is my BT Card, HS04 my TouchScreen device and HS05 the webcam. HS03, HS04, HS05 needs to be 0xFF in MaciASL so:

6. Go back to MaciASL and Find in the left menu HS01, HS02... etc.
<img width="516" alt="schermata 2017-09-03 alle 23 09 28" src="https://user-images.githubusercontent.com/22716366/30006629-f5669786-90fc-11e7-9f6b-1078b2b99a79.png">

7. Edit the second value of you internal devices with 0xFF (highlighted one in picture):
<img width="497" alt="schermata 2017-09-03 alle 23 11 53" src="https://user-images.githubusercontent.com/22716366/30006650-5065537a-90fd-11e7-9565-62f14a8088c1.png">

As you can see under Scope(HS04) i've edited the second value to 0xFF (it was 0x03). Do this for all the internal devices.

8. When you have done press Compile (no errors should show up), then File -> Save As, and as File Format: ACPI Machine Language Binary. Save in EFI/Clover/ACPI/patched.

9. Reboot.

Let me know if this fixed your issue. I leave my config.plist file and my SSDT-XHC.aml for reference. Thank you and Good Luck!

Note: if after reboot for some reason you get "BT Not Available" error, try to sleep and wake. BT will work again and you will not have this problem anymore.

[reference-files.zip](https://github.com/syscl/XPS9350-macOS/files/1273257/reference-files.zip)

**Comment by se1ya** [comment]
good morning,
i tested the changing in the SSDT file an after sleep of shut down the display, the wifi is working with the same speed very well. im now on the road with my notebook. so at the evening i will know more. 
the first test shows great. THX for our walkthrough

**Comment by ZombieTheBest** [comment]
@se1ya Let me know! 255 means "internal" so initially i translated it to 0x255, realizing later that in HEX is 0xFF (while writing this guide). So i've changed to 0xFF, but started to get BT problems. Reverted back to 0x255 and everything seems to work (lol). So, let me know if 0xFF works for you as I think is the correct value.

**Comment by bozma88** [comment]
@ZombieTheBest, I think your conclusion is correct.
I never, ever had issues with Wifi on my system, and if you have a look at the files of my 9360 TMX guide, the connectors are already FF-patched (by using UIAC SSDT).
Have a look at my latest assets on tmx [here](https://www.tonymacx86.com/threads/guide-dell-xps-13-9360-on-macos-sierra-10-12-x-lts-long-term-support-guide.213141/)!

**Comment by ZombieTheBest** [comment]
@bozma88 Nice, thank you for your feedback. Let's hope this solves the issue! 👍

**Comment by syscl** [comment]
@ZombieTheBest Thank you for you information! 

I have added your SSDT-XHC to this GitHub, please try and see if it works.

Again, thank you!
syscl

**Comment by ZombieTheBest** [comment]
@syscl Don't know if XHC pattern is the same for everyone, we'll see!

**Comment by se1ya** [comment]
okay, i tested the new deploy, and keyboard and trackpad are complete off. touchscreen, wifi and usb ports working. i try to install an older deploy but has no effects

**Comment by ZombieTheBest** [comment]
@se1ya No idea about what happened. Seems something related to VoodooPS2 kext. Try to reinstall the kext. What about WiFi? Still working great after sleep?

**Comment by se1ya** [comment]
@ZombieTheBest  okay i reinstall the vodoo kext and everything is fine. now my ping test

after booting:
![screenshot 2017-09-05 08 22 54](https://user-images.githubusercontent.com/16716560/30047858-a765cbac-9213-11e7-9bb8-ff5141027267.png)

after sleep:
![screenshot 2017-09-05 08 23 53](https://user-images.githubusercontent.com/16716560/30047870-bebe3410-9213-11e7-83aa-ec6591de9ecf.png)

and after display shutdown:
![screenshot 2017-09-05 08 24 15](https://user-images.githubusercontent.com/16716560/30047882-d44299ca-9213-11e7-9b0d-a508da06f85d.png)

it looks good at my home network. i will test it the day in university and work with different networks.
THX for help 👍

**Comment by ZombieTheBest** [comment]
Swapped my card with DW1560. I confirm fix works for this card too (and no more BT problems!)

**Comment by syscl** [comment]
Thank you!@ZombieTheBest

**Comment by x4080** [comment]
@ZombieTheBest do you use it in Windows 10 as well? Mine is not working well in windows 10
