### ISSUE TITLE
Problem with latest Deploy... Urgent

### ISSUE THREAD

**Issue by markymmp** [syscl/XPS9350-macOS#148]
Ok so i just ran the new reply and when rebooted it now runs into a kernel panic... How can i revert back to the previous EFI rater than having to reinstall from scratch again... Like making a bootable clover efi to get me back in to boot to the os... I've installed lots if dj software and it too ages to do.. should of waited i guess... grrrrr.

**Comment by markymmp** [comment]
I`ts ok I've just fixed it... created a back up on a usb stick .. just incase.. PS the new deploy doesn't work for me..

**Comment by syscl** [comment]
What kernel panic it gave you?

syscl

**Comment by markymmp** [comment]
Hi Sorry looked like one.. Ok so what it does is after the clover screen it displays text on the screen I've not seen before and then stops and reboots.. it goes into a loop.. I can only get it to boot by booting from a USB disk I've created with an old Deploy from a couple ago when the function keys were not functioning well.. I have taken pictures.. It's been stable since todays update and when I retried to re- reply.sh from the last one it returned a number of failures .. hope you can help

**Comment by markymmp** [comment]
Kind Regards

(Marky) Mark P

Skype: Marqnet
.…….………………………………...........

**Comment by markymmp** [comment]
emailed picture didn't work

**Comment by markymmp** [comment]
any chance of reverting back to the previous repo please or ping a link so I can put this back how it Was..

**Comment by jerryzj** [comment]
看起來像是voodoo觸控版出了問題

**Comment by jerryzj** [comment]
我更新完也掛了

**Comment by markymmp** [comment]
感謝您發現它@jerryzj。我已經恢復到舊的部署，直到這是固定的

**Comment by syscl** [comment]
Voodoo触摸板的问题吗？

这就比较奇怪了请问能提供一下图片或者日志吗，因为我的XPS现在在朋友那里。

谢谢

syscl

**Comment by jerryzj** [comment]
@syscl 

https://imgur.com/a/G1ewh

**Comment by yasster** [comment]
@syscl Got the same issue with @jerryzj kernal panic

**Comment by syscl** [comment]
Thank you for the picture. Please try remove VoodooPS2 to see if it can boot or not(will lose trackpad and keyboard support)..

syscl

**Comment by markymmp** [comment]
Same as mine too. 

Kind Regards

(Marky) Mark P
.…….………………………………...........

**Comment by xaek** [comment]
Kernel panic is due to AirportBrcmFixup.kext
Remove it.

**Comment by syscl** [comment]
Thank you!

syscl

**Comment by markymmp** [comment]
Fantastic work guys the latest deploy fixes the KP . I'll close the thread...

Kind regards and respects

Marky P
