### ISSUE TITLE
Kp 求助 

### ISSUE THREAD

**Issue by shixuev5** [syscl/XPS9350-macOS#15]
![image](https://cloud.githubusercontent.com/assets/3207014/21232306/16726842-c326-11e6-8e43-90c43b776db8.jpeg)

运行脚本之后 重启卡在这 应该不是kext跟dsdt 之类的问题 我用另一个u盘 只放安装用的也会卡这

**Comment by syscl** [comment]
@shixuev5 用我最新的config.plist

**Comment by shixuev5** [comment]
@syscl  用新的deploy.sh 重新弄了一遍 问题解决了 但是 蓝牙貌似不能用 设置里面没有蓝牙选项。

**Comment by syscl** [comment]
@shixuev5 蓝牙问题 重启到windows重新关闭再打开一遍试一试

syscl
