### ISSUE TITLE
Dw1560 wifi not found and DSDT compile errors

### ISSUE THREAD

**Issue by vinv** [syscl/XPS9350-macOS#155]
Trying these instructions and patches on a 9350 in which I replaced the wifi card with a DW1560, I've run into 2 problems -
1) The wifi card is not detected. Wireless does not show up as a network option during install and after. The card was working fine in Windows.
2) The DSDT compilation step of deploy throws weird errors. The tool complains that ".dsl" is not found for all 3/4 steps. It actually says ".dsl" as if the name passed into the "compile_table" routine was blank. The script proceeds, but am not sure it did everything it was supposed to.

I don't know if the 2 problems are related. Any ideas?

**Comment by ZombieTheBest** [comment]
Which OS version are you running? Please provide your clover folder

**Comment by squash-** [comment]
@vinv i've noticed either with the newer versions of clover or with new bios versions that the SSDTs get dumped as says SSDT-0-SataTabl.aml. 

The Deploy script has issues finding these tables/dsl files because of the new naming scheme. If you rename all of the SSDTs to remove the table name after the SSDT number, it will patch and compile everything fine.

**Comment by vinv** [comment]
@squash: I'll try that. Does any of this also explain the wifi not working? I thought the DW1560 was supported OOB.

@ZombieTheBest: Sierra. I'll upload the clover folder from the ssd/efi in a bit.

**Comment by vinv** [comment]
@squash- Thanks, that was the problem. When I renamed the files as suggested, everything compiled without error.

My WiFi issue was due to this - http://www.insanelymac.com/forum/topic/312759-fix-macos-sierra-dp1-bcm94532z-wifi/. WiFi now works fine.

**Comment by squash** [comment]
Removing myself from this thread as I was tagged by mistake
