### ISSUE TITLE
Black screen after apple logo

### ISSUE THREAD

**Issue by Eduardoveras** [syscl/XPS9350-macOS#163]
I shut down my laptop a few hours ago and now when I try to boot it doesn't pass the apple logo, tried with -v and -x flags and nothing, the screen goes black after the apple logo (in the moment it usually changes resolution)

**Comment by Eduardoveras** [comment]
Went back to windows until december, it was great having a dell-mac for a few months (until it crashed) lol Thanks everyone for your hard work!

**Comment by syscl** [comment]
Hello, what configuration you use?

**Comment by Eduardoveras** [comment]
XPS-13 9350, Samsung 250GB nvme M.2 SSD, Skylake i5, 8gb ram,
