### ISSUE TITLE
High Sierra Appstore Update not working.

### ISSUE THREAD

**Issue by markymmp** [syscl/XPS9350-macOS#165]
Hi guys just wondered if anyone has managed to upgrade from the App Store on their 9350.. I have tried 3 times and to no luck.. I also noticed my clipboard (Copy Paste) has stopped working and I've updated to the latest deploy too.. Otherwise.. My Hackbook is the envy of most of my mates with Mac's ;-)

**Comment by markymmp** [comment]
Hi guys do you have to do a fresh install or is it possible . as I've tried a number of times?  I'd rater not have tot restart from scratch again.. oh for the record I use it to DJ with and its solid..

**Comment by markymmp** [comment]
Anyone?

**Comment by R1MnTnA** [comment]
@markymmp check or post your question on the tonymac forums.

**Comment by markymmp** [comment]
ok thanks will do.

**Comment by markymmp** [comment]
Fixed and added lily.kext for sierra
