### ISSUE TITLE
9360 8th gen kernel panic (Sierra install)

### ISSUE THREAD

**Issue by x8BitRain** [syscl/XPS9350-macOS#168]
I'm guessing it's something to do with the CPU not being supported (i5  8250U) but I'm getting a kernel panic due to wrong CPU addresses I think. Here's a pic of verbose mode: https://i.imgur.com/k9pgQOb.jpg

Anything at all I can do to fix this? Thanks.

**Comment by R1MnTnA** [comment]
For the 9360 model use this guide.- https://www.tonymacx86.com/threads/guide-dell-xps-13-9360-on-macos-sierra-10-12-x-lts-long-term-support-guide.213141/
