### ISSUE TITLE
Update to 10.12.2

### ISSUE THREAD

**Issue by x4080** [syscl/XPS9350-macOS#17]
Hi anybody sucess updating to 10.12.2? I download and when it ask for restart, the restart process seems trying to install things but the mac is already restart before it finishes, maybe thats the problem but I dont know why that happened

Thanks

**Comment by icedman** [comment]
i had the same problem.
do not download from app store.

download combo updater. link:
https://www.tonymacx86.com/threads/macos-10-12-2-update.209122/

**Comment by syscl** [comment]
@x4080 @icedman It's weird, I updated it directly from the App Store...

**Comment by gctseng** [comment]
@x4080 @icedman Me as well. I had updated to the latest deploy.sh as of the Thursday morning commit and then directly updated to 10.12.2 from App store.

Dell XPS 13 9350 - Processor Intel® Core™ i7-6560U (Skylake-6th Gen/Dual Core/4MB Cache) - Graphics Intel® Iris™ 540 - Display QHD+ Touch (3200x1800) (276 ppi) - RAM 16GB - Storage 512GB NVMe (Toshiba 512gb THNSN5512GPU7)

**Comment by x4080** [comment]
@icedman you use combo updater and works? Its not because in our dell config? Because of the file?

**Comment by x4080** [comment]
@syscl and @gctseng do you successfully update or not using app store directly ? Confused with can or not :)

**Comment by x4080** [comment]
Using combo still not works, I think the process is still the same, it just extract in a folder and requires restart to install the update which is already restarted before it even finish installing the updates

**Comment by syscl** [comment]
@x4080 @icedman @gctseng please try this one, maybe I mismatch the SMBIOS in my github, that's the reason why you cannot update directly. Sorry.


[config.plist.zip](https://github.com/syscl/XPS9350-macOS/files/658934/config.plist.zip)
syscl

**Comment by gctseng** [comment]
@x4080 Confirmed I successfully updated using app store directly.  The computer rebooted (or at least I think it did--I didn't watch that carefully) and and went into the screen where it installed the update.

**Comment by syscl** [comment]
Now, there's two version of the config.plist, let me clarify:
- MacBook8,1 for non-hwpenable
- MacBook9,1 for hwpenable

I will release the MacBook9,1 with hwp enable. Be sure to test it yourself, it may eat your cat.

syscl

**Comment by x4080** [comment]
@syscl thanks and don't worry it's not your fault, and you're already in 10.12.2? 

@gctseng that's interesting, did you check in about page that it now had 10.12.2? Sorry for doubt, I was certain that it successfully install but it was not

**Comment by syscl** [comment]
@x4080 you can see my pic in issue #10 , already 10.12.2

syscl

**Comment by x4080** [comment]
@syscl Thanks, I'll try again your suggestion

**Comment by x4080** [comment]
@syscl, I run your deploy from start and now it's working (installing update) hope nothing bad will happen 

Thanks for everything
