### ISSUE TITLE
Security Update 2018-001 causing my XPS to crash

### ISSUE THREAD

**Issue by markymmp** [syscl/XPS9350-macOS#176]
Hi Guys i've had to revert back to my old 9350 config on another SSD as the security update causes it to crash. Anyone else resolve this issue?

**Comment by syscl** [comment]
@markymmp Do you try to update the Lilu to see if this solve the problem?

syscl

**Comment by markymmp** [comment]
Hi @syscl i failed in updating to High Sierra just couldn't get clear instructions what to change to get it to reboot in the upgrade so i' still on Sierra. Lilu is for High `Sierra right ? I will try again on my other SSD from fresh when i have time to play :-)

**Comment by markymmp** [comment]
@syscl `lily will only work with High Sierra right? i'm going to try the upgrade again but dropping in the lilu.kext and the apfs one.

**Comment by syscl** [comment]
Lilu will work with 10.12.x (Sierra) as well. 

New Lilu only add support for 10.13.x.

syscl

**Comment by markymmp** [comment]
Yup that worked @syscl thank you.. I guess when i want to upgrade to HS i just need to add the new Lilu.kext and the APFS.kext and it should upgrade? I'm happy with it in Sierra as its a working hackintosh meaning i DJ with it and it hasn't crashed yet :-)

**Comment by syscl** [comment]
Yes, you can update apfs from my github.

**Comment by markymmp** [comment]
Thankyou @syscl
