### ISSUE TITLE
SSDT-XPS13SKL.aml not found in patched

### ISSUE THREAD

**Issue by x4080** [syscl/XPS9350-macOS#19]
Hi @syscl , I just check in my patched folder that SSDT-XPS13SKL.aml is not exists, is this still used? Or have to copy it manually ? 

Is this why my thunderbolt3 is not working?

Thanks

**Comment by syscl** [comment]
@x4080 See recent update, I include SSDT-XPS13SKL.aml already.

syscl

**Comment by x4080** [comment]
Cool, is before its not available? What is this SKL improve?

**Comment by syscl** [comment]
@x4080 I don't know, I just saw real MacBook(SKL) has this SSDT, thus I stripped it down and inject to our laptop.

syscl

**Comment by x4080** [comment]
Ok cool
