### ISSUE TITLE
Running list of issues?

### ISSUE THREAD

**Issue by jethrokuan** [syscl/XPS9350-macOS#2]
Is there a running list of issues I should be aware of before installing this? I'm looking to run OSX as my main dev environment.

**Comment by syscl** [comment]
@jethrokuan I've been testing XPS 13 as a daily drive, till now the minor bug is the trackpad pref and multi finger(you can use VoodooPS2 instead to solve this issue). But, I prefer AppleSmartTouchPad and I will wait the author to fix the issues.

syscl

**Comment by gctseng** [comment]
Are you using the original WiFi/Bluetooth adapter or did you replace it?

**Comment by syscl** [comment]
@gctseng I replaced DW1820 to much better one: DW1830 which works OOB.

syscl
