### ISSUE TITLE
I Wonder... Could DW1560 still be used successfully?

### ISSUE THREAD

**Issue by imcsq** [syscl/XPS9350-macOS#201]
My XPS13 works not so well with a DW1830, which turns out a high delay (maybe due to my poor added antenna setting). So I tried my DW1560 bought before instead. The net works well on both windows and Mac without patch,  but after patching DSDT mac couldn't boot anymore... I wonder if the script could still work well with DW1560 (even if some easy modified on script is needed) and if there's a way in which i could use my DW1560. Thanks a lot.

**Comment by imcsq** [comment]
In detail: XPS9350 i7-6560u + DW1560 + BIOS 1.7.0 (have renamed dsdt files already)

I found it could boot successfully only when I didn't inject #RP13 in syscl_ltrovr. If I do this patch, mac booting would stop at here.

![image](https://user-images.githubusercontent.com/7814845/41109289-3fe8bfc4-6aa9-11e8-87a5-d9a2a4640c30.png)
![image](https://user-images.githubusercontent.com/7814845/41109304-46b75cac-6aa9-11e8-85a1-0691d5cad844.png)

ACPI: 
[origin.zip](https://github.com/syscl/XPS9350-macOS/files/2081037/origin.zip)

Is the use of DW1560 to be blamed for? Appreciate it a lot if there's a request. @syscl

**Comment by chisacam** [comment]
simple solution!
[wifi.zip](https://github.com/syscl/XPS9350-macOS/files/2084539/wifi.zip)
download it and install with kext utility
install is done, reboot.
wifi will be fine

i'm using i5, qhd+, dw1560.

**Comment by imcsq** [comment]
@chisacam Thanks a lot. But I still couldn't boot the system as the picture showed if I run the script for patch. Is it the fault of DW1560 or other things? Did this happen to you when you run script?

**Comment by chisacam** [comment]
@imcsq Yes, run Deploy script and booting work fine, and install that kext, reboot again, wifi is work.
if your clover config's smbios name is macbookpro13,2 , must change macbookpro13,1
clover is block boot when name is macbookpro13,2 at my xps13.

**Comment by imcsq** [comment]
@chisacam  Thanks a lot. Could you plz share your CLOVER with me? Even if my XPS 13 is a model with i7 6560u. I really cannot boot if I patch inject #RP13 in syscl_ltrovr and use i2cVoddoo. 

And again, I pardon @syscl for solution of my issue. Anything wrong?

**Comment by chisacam** [comment]
[CLOVER.zip](https://github.com/syscl/XPS9350-macOS/files/2085577/CLOVER.zip)
here is my CLOVER 
plz regen serial if replace it.
and i use the non-iris model, and not patch #RP13. just run Deploy.sh...
good lock guy

**Comment by imcsq** [comment]
@chisacam Thanks a LOT! You are so sweet. But your CLOVER didn't work as well, which urge me to look into my BIOS settings. I finally restore my BIOS settings and everything goes well. Maybe some settings on keyboard went wrongly after update my BIOS. Now I could boot normally.

What's more, if the updated CLOVER is privated, you could delete it! I've delete it already. Thank you again!

(And, in fact, REP13 is also a part of Deploy.sh Haha~)

**Comment by x4080** [comment]
@imcsq I having problem with DW1560 in windows 10, what driver do you use ? I use windows 10 driver - I guess and the wifi is so weak and sometimes cannot even connect

**Comment by maz-1** [comment]
> @imcsq I having problem with DW1560 in windows 10, what driver do you use ? I use windows 10 driver - I guess and the wifi is so weak and sometimes cannot even connect

Are you using windows insider preview 1903?

**Comment by x4080** [comment]
I dont think so, because I never subscribe to be the insider, so it should be normal in normal windows 10 ?
Thanks @maz-1 for answering since I look everywhere and seems everyone is just give up this wifi card on windows 10

The irony is that, I wait for so long to replace this card to use it in Mac and now windows is not working :)

**Comment by maz-1** [comment]
> I dont think so, because I never subscribe to be the insider, so it should be normal in normal windows 10 ?
> Thanks @maz-1 for answering since I look everywhere and seems everyone is just give up this wifi card on windows 10
> 
> The irony is that, I wait for so long to replace this card to use it in Mac and now windows is not working :)

Using DW1830 on windows 10 and get similar problem recently ( low speed and ping router drops badly ). I guess some updates on windows 10 breaks broadcom wireless.

**Comment by x4080** [comment]
@maz-1 Ah, maybe that is the problem. guess we should wait for microsoft to fix it then

**Comment by maz-1** [comment]
> @maz-1 Ah, maybe that is the problem. guess we should wait for microsoft to fix it then

Maybe install another driver instead of dell provided ones?
DW1830 is mostly identical to BCM43602 on MacBookPro11,5 so I downloaded bootcamp dmg using https://github.com/timsutton/brigadier, extracted and installed wifi driver. A lot better now.
This is possibly a problem specific to drivers provided by dell.

**Comment by x4080** [comment]
Thanks for the tip @maz-1 , will windows block to install the driver ? saying like it already has the latest driver ? it says it when I tried to install before from broadcom HP I think.

edit : Do you mean DW1560? I use DW1560
