### ISSUE TITLE
Mojave Support?

### ISSUE THREAD

**Issue by tlefko** [syscl/XPS9350-macOS#205]
Hello Everyone, I was wondering if this currently has any support for Mojave? If not, is there a chance of it happening? Any feedback would be appreciated!

**Comment by syscl** [comment]
Hi there will be Mojave support.

**Comment by tlefko** [comment]
Hey, thanks for your speedy reply. Do you know when that would be?

I understand your busy obviously with exams and I appreciate your publishing the project.

I'm happy to test it now and see what bugs I find in Mojave

**Comment by tlefko** [comment]
For me most of your deploys have worked well except sometimes trackpad is broken so I just use voodoops2 instead
