### ISSUE TITLE
Dell 1820A Wireless Card

### ISSUE THREAD

**Issue by bdurrow** [syscl/XPS9350-macOS#22]
I have not had any luck using the included Dell 1820A card based on the BCM4350.  It seems that there is either a USB (or perhaps UART communication) problem or the Card doesn't power on the radio.

**Comment by syscl** [comment]
@bdurrow We are all out of luck with a DW1820 on XPS 13 9350. Maybe we can develop a binary patch for DW1820, but it takes us time to explore. So, I simply switch default wireless card to DW1830 which works OOB. 

syscl

**Comment by bdurrow** [comment]
I thought the DW1830 had 3 antenna connectors but there was only support for 2 on the included antenna harness.  I ordered a BCM94352HMB based card (https://smile.amazon.com/gp/product/B00JY6X9HM/).  It should arrive tomorrow and hopefully it will work without trouble.

**Comment by bdurrow** [comment]
I would suggest mentioning DW1820A status in the README.md.  It would save people a lot of troubleshooting.

**Comment by syscl** [comment]
Yes, it's 3 antenna, but you can:
- Order a new antenna 
- Leave one antenna empty(no side effect)

The first solution has been applied for my Dell Precision M3800(QHD+), the second solution has been applied for XPS 13 9350. 94352HMB can be powered up, but you need one additional patch name fcvo, that's the reason why I drop that card...


syscl

**Comment by bdurrow** [comment]
Is this the patch you are referring to? http://www.insanelymac.com/forum/topic/312759-fix-macos-sierra-dp1-bcm94532z-wifi/

Are there side effects to using that patch?  It seems that we could use the detection code you similar to how you set gBluetooth_Brand_String in Deploy.sh to see if this patch would be required.

A little off topic but I don't see that you use gBluetooth_Brand_String after setting it.

**Comment by syscl** [comment]
Yes, that's the patch you have to apply for your card on Sierra. 

syscl

**Comment by Xplic1T** [comment]
Sys if I replace onboard card with a DW1830, will everything work after I Deploy.sh (i.e. have you already attached the needed ktexts and stuff) ?

**Comment by syscl** [comment]
@Xplic1T DW1830 works OOB, deploy.sh just install FakePCIID to make macOS identify it as AirPortExtreme...

syscl

**Comment by dudenesspa** [comment]
Only getting 450mbps on ac wireless. Getting 1100-1300 when in Windows. Had several 1560 prior. Removed those patches from config except for handoff patch. Handoff not working either.
