### ISSUE TITLE
Combojack安装失败

### ISSUE THREAD

**Issue by carking** [syscl/XPS9350-macOS#220]
已经关闭SIP,安装后重启不启作用 重建也不起作用
<img width="1057" alt="screen shot 2018-12-28 at 7 28 41 pm" src="https://user-images.githubusercontent.com/33761091/50514400-ddafa400-0ad8-11e9-9cbd-58e7dc862a76.png">

**Comment by carking** [comment]
KEXT已经在CLOVER中，重装系统也无法解决

**Comment by syscl** [comment]
谢谢 我正在完善这个项目

**Comment by maz-1** [comment]
你是用applealc驱动的吗，layout id 13?

**Comment by carking** [comment]
> 你是用applealc驱动的吗，layout id 13?

是的，用的别人的CLOVER都是APPLEALC+LiIU驱动的，就是这个COMBOJACK死活无法安装导致耳机孔无法正常使用

**Comment by maz-1** [comment]
系统进程里看不见ComboJack吗

**Comment by carking** [comment]
> 更新一下：https://github.com/hackintosh-stuff/ComboJack
> 看下系统进程里有没有ComboJack

你的我也试过了，都是安装不成功，重启后没有效果，进程没有，插入耳机没有对话框，还试过重装10.13 10.14
我的问题和这个10楼的一样
https://www.tonymacx86.com/threads/guide-dell-xps-9350-mojave-virtualsmc-i2c-trackpad-clover-uefi-hotpatch.267161/page-2

安装时候提示Not a directory是不是代表有问题？

**Comment by maz-1** [comment]
/usr/local/sbin 这个目录你有吗

**Comment by carking** [comment]
> /usr/local/sbin 这个目录你有吗

有
<img width="914" alt="screen shot 2018-12-29 at 9 44 08 am" src="https://user-images.githubusercontent.com/33761091/50532102-4afe1c00-0b4f-11e9-9eba-d87b7ad27858.png">
<img width="884" alt="screen shot 2018-12-29 at 9 44 16 am" src="https://user-images.githubusercontent.com/33761091/50532103-4afe1c00-0b4f-11e9-92a4-ba86461f3291.png">

**Comment by maz-1** [comment]
> > /usr/local/sbin 这个目录你有吗
> 
> 有

你这应该是没有这个目录，然后ComboJack被复制到/usr/local/sbin这个文件了
是我没注意，因为我装了homebrew所以默认就有这个目录
你删掉 /usr/local/sbin然后下最新的再安装一遍吧

**Comment by carking** [comment]
> > > /usr/local/sbin 这个目录你有吗
> > 
> > 
> > 有
> 
> 你这应该是没有这个目录，然后ComboJack被复制到/usr/local/sbin这个文件了
> 是我没注意，因为我装了homebrew所以默认就有这个目录
> 你删掉 /usr/local/sbin然后下最新的再安装一遍吧

你好，我把我SBIN.EXEC这个文件删除，手动新建了SBIN的文件夹，再次安装，重启后还是不生效，没有弹窗口，但是进程中有COMBOJACK
<img width="1216" alt="screen shot 2018-12-29 at 10 19 54 am" src="https://user-images.githubusercontent.com/33761091/50532446-5e5fb600-0b54-11e9-9331-1d7f92896fdf.png">

**Comment by maz-1** [comment]
你按照说明来了吗
* 用AppleALC驱动声卡，layout id使用13（用别的layout id外置麦克风用不了）
* 删掉CodecCommander
* 把VerbStub.kext放到Clover/kexts/Others
* 运行install.sh安装，重启
* IORegistryExplorer搜索一下有没有VerbStubUserClient

再不行终端运行

    sudo launchctl unload /Library/LaunchDaemons/com.XPS.ComboJack.plist
    sudo /usr/local/sbin/ComboJack

插一下耳机，看一下终端有什么输出。

**Comment by carking** [comment]
> 你按照说明来了吗
> 
> * 用AppleALC驱动声卡，layout id使用13（用别的layout id外置麦克风用不了）
> * 删掉CodecCommander
> * 把VerbStub.kext放到Clover/kexts/Others，重启
> * IORegistryExplorer搜索一下有没有VerbStubUserClient
> 
> 再不行终端运行
> 
> ```
> sudo launchctl unload /Library/LaunchDaemons/com.XPS.ComboJack.plist
> sudo /usr/local/sbin/ComboJack
> ```
> 插一下耳机，看一下终端有什么输出。

换了个正确CLOVER后已经搞定，奥力给，多谢老哥，我的错误就在于SBIN不是文件夹而是EXEC文件，手动建立文件夹后就OK，请问为什么会发生这种情况？

**Comment by maz-1** [comment]
> 
> 换了个正确CLOVER后已经搞定，奥力给，多谢老哥，我的错误就在于SBIN不是文件夹而是EXEC文件，手动建立文件夹后就OK，请问为什么会发生这种情况？

装过homebrew会自动建立这个目录，比如我
所以没考虑到/usr/local/sbin/不存在的情况
