### ISSUE TITLE
Shutdown -> Restart if theres disk connected to USB

### ISSUE THREAD

**Issue by x4080** [syscl/XPS9350-macOS#29]
Hi I get this when xps is shutdown with flash disk is connected to USB, and when I'm using recovery partition with the same clover, it shutdown normally

**Comment by syscl** [comment]
@x4080 

Nice, I found the same issue on XPS 13 too! 

syscl

**Comment by x4080** [comment]
Cool :)

**Comment by syscl** [comment]
@x4080 try the latest deploy.sh

syscl

**Comment by x4080** [comment]
I will thanks

**Comment by x4080** [comment]
This one still persists, and I dont know if this related or not, I add app in the user groups-login items, and after it restarts/after shutdown, the new item is dissapear in login items list 

Do you experience this as well? The weird thing is some of the app exists, so I dont know how to replicate this

**Comment by bozma88** [comment]
I solved it with `usb_prw_0x6d_xhc_skl` DSDT patch.

**Comment by syscl** [comment]
@bozma88 I've already included that patch very long time ago.

Could you confirm this work?(I double it won't)

I will back to my house tonight to see if the patch fail to apply.

syscl

**Comment by syscl** [comment]
@bozma88 I further confirmed that usb_prw_0x6d_xhc_skl has injected correctly.

Thus this patch seems no effect..

syscl

**Comment by syscl** [comment]
@x4080 give latest deploy.sh a try! Report if shutdown -> restart issue is solved or not.

In my case, shutdown -> reboot issue is gone. If I eliminate shutdown patch, then shutdown becomes reboot again. 

Good luck!
syscl

**Comment by x4080** [comment]
Cool, I'll let you know

**Comment by x4080** [comment]
Looks good, connecting a usb disk get no restart, will try it with other external ssd

**Comment by syscl** [comment]
@x4080 Thank you for your information.

Could you also try plug-in USB-C device then shutdown?

Thank you,
syscl

**Comment by x4080** [comment]
I'll try it

**Comment by syscl** [comment]
@x4080 Thank you!

syscl

**Comment by syscl** [comment]
@x4080 how does your XPS 13 9350 behave? Encounter any Shutdown -> reboot issue these days?

syscl

**Comment by x4080** [comment]
No didnt have any yet

**Comment by syscl** [comment]
@x4080 Nice.

Try the latest deploy to see if the Wi-Fi is a bit faster!

syscl

**Comment by x4080** [comment]
Sure but I'm still using usb wifi , is it affected also ?

**Comment by syscl** [comment]
Better to switch to dw1830 or dw1560

syscl

**Comment by x4080** [comment]
Yeah I think so too

**Comment by syscl** [comment]
After one week testing, seems there's no more shutdown -> reboot issue. I can't be happier!

syscl
