### ISSUE TITLE
Restart problem?

### ISSUE THREAD

**Issue by x4080** [syscl/XPS9350-macOS#3]
Hi, I just realized that I cannot restart, shutdown and sleep seems ok, do you have this issue as well? 

Thanks

**Comment by syscl** [comment]
HaltEanbler=Yes see my config.plist

**Comment by x4080** [comment]
Thanks, I'll try it

**Comment by x4080** [comment]
So Haltenabler and resetAddress ?

<key>HaltEnabler</key>
		<false/>
		<key>ResetAddress</key>
		<string>0xB2</string>
		<key>ResetValue</key>
		<string>0x73</string>

**Comment by x4080** [comment]
I did above settings and success, thanks
