### ISSUE TITLE
This is a Masterpiece! Thank You!

### ISSUE THREAD

**Issue by R1MnTnA** [syscl/XPS9350-macOS#30]
I hope I can leave this here. You have just saved my life. Been working on my XPS for days and this is the only thing that actually works! One question though, I see you are using the DW1830, but does the 5ghz work on it with your kexts and config?

Thanks again.

**Comment by syscl** [comment]
@rpiangozza Thank you.

Yes, 5G work without any additional kext patches.

syscl

**Comment by rpiangozza** [comment]
Awesome. Currently I have the 1560 in the laptop because that what was recommended in that old guide on Tonymac forum. Do you think if I just swap it out and put back the 1830 it would work or would I need to rerun your script?

**Comment by rpiangozza** [comment]
crap I just looked at the the module and I have the DW1820A. :-(

**Comment by syscl** [comment]
@rpiangozza Don't need swap to DW1830 if you've already installed DW 1560. Both DW 1560 and DW 1830 are good wireless card IMO. I enjoy both of them.

The only thing you need for DW 1560 is to add one line of kext patch, here's the patch:
```
Kext:    AirPortBrcm4360
Find:    81F952AA00007529 
Replace: 81F952AA00006690
```

Through Clover config.plist
```
<dict>
	<key>Comment</key>
	<string>AirPortBrcm4360 - fcvo</string>
	<key>Disabled</key>
	<false/>
	<key>Find</key>
	<data>gflSqgAAdSk=</data>
	<key>Name</key>
	<string>AirPortBrcm4360</string>
	<key>Replace</key>
	<data>gflSqgAAZpA=</data>
</dict>
```

All credit goes to @the-darkvoid who figure out the patch.

DW 1820 may work on XPS 13 in theory, but I just want my life be simple so I replace it. Maybe need binary patch for DW 1820 to work on XPS 13. In M3800/XPS9530, DW 1820 can work out of box but behave unstable under Sierra.

syscl

**Comment by rpiangozza** [comment]
You are a saint and Amazingly smart! I'm still learning and trying to figure this all out and you have been such a great help. I can only hope to get up to your level of expertise! :-D 

I'll let you know how the DW1820 works out or maybe I'll just buy a 1830. I read on the forum that you though it was better with more antennas.
 :-)
Thanks again and I'll keep a watch for any updates from you here or on the forums. All the best to you!

**Comment by x4080** [comment]
@syscl if you can make DW1820 works, I will save $30 :)

**Comment by sajithdilshan** [comment]
This indeed is a Masterpiece. But is it legal to run MacOS on a non-apple hardware?

**Comment by adamjames** [comment]
@sajithdilshan Doing so constitutes a violation of Apple licensing agreements, yes. However, as far as I understand it (I may be incorrect), the project developer is free to distribute what are essentially instructions - the person following the instructions needs to weigh up the options (and potential consequences, however remote) themselves.

**Comment by R1MnTnA** [comment]
@sajithdilshan It's legal to make or distribute information online. If you'd like more information then please do a google search on yhe topic that is not a question for this place.
