### ISSUE TITLE
No brightness-keys on latest deploy with VoodooPS2Controller

### ISSUE THREAD

**Issue by furrybanana** [syscl/XPS9350-macOS#32]
Hi syscl,
thank you for this awesome script. It helped me a lot with my Dell XPS 13 9350 as to I am able to use it daily with Hackintosh.

As of the latest deploy I tried the Voodoo option on the PS2Controller. While ApplePS2Smart (was used before I think) I experienced some bugs on clickpad I just wanted to give some feedback here: touchpad on Voodoo is working but my screen brightness after a cold boot always is maxed out and the F11/F12 button for brightness are not working.

My Dell XPS specs:
model 13 9350 FullHD 
i5 6200u
8GB Ram
Samsung NVMe PM951 256GB
Wifi Broadcom 1830 (good value and works flawless, thank you for the recommendation)

macOS Sierra 10.12.3 (updated yesterday, fully working before the latest deploy-script)

With kind regards.

**Comment by syscl** [comment]
@furrybanana Hi, could you please provide your origin and patched ACPI tables for me?

Thank you,
syscl

**Comment by syscl** [comment]
@furrybanana And the running result of 
```sh
./deploy.sh -d
```

syscl

**Comment by furrybanana** [comment]
do you experience bugs when trying to right click (graphic glitches, opening files multiple times) you can escape with ESC ? or is this just a bug on my machine? having the same randomly on the Voodoo, too.

[ACPI.zip](https://github.com/syscl/XPS9350-macOS/files/730677/ACPI.zip)
[deploy.debug.txt](https://github.com/syscl/XPS9350-macOS/files/730679/deploy.debug.txt)

**Comment by syscl** [comment]
@furrybanana No, I haven't experience any of this bugs with AppleSmartTouchPad/VoodooPS2.

You probably do not use my Clover folder and don't follow the step.

About brightness key, you should restore all setting in keyboard shortcuts, especially brightness key's setting.

syscl

**Comment by furrybanana** [comment]
hi,
as far as I know I did move your CLOVER folder to EFI and followed the readme  :)

**Comment by syscl** [comment]
Also, I notice that you manually install VoodooPS2 in your system, you need to remove it.

syscl

**Comment by syscl** [comment]
@furrybanana see here
```sh
kext-dev-mode allowing invalid signature -67062 0xFFFFFFFFFFFEFA0A for kext VoodooPS2Trackpad.kext
kext-dev-mode allowing invalid signature -67062 0xFFFFFFFFFFFEFA0A for kext VoodooPS2Mouse.kext
kext-dev-mode allowing invalid signature -67062 0xFFFFFFFFFFFEFA0A for kext VoodooPS2Keyboard.kext
kext-dev-mode allowing invalid signature -67062 0xFFFFFFFFFFFEFA0A for kext VoodooPS2Controller.kext
kext-dev-mode allowing invalid signature -67062 0xFFFFFFFFFFFEFA0A for kext CodecCommander.kext
kext-dev-mode allowing invalid signature -67062 0xFFFFFFFFFFFEFA0A for kext BrcmPatchRAM2.kext
kext-dev-mode allowing invalid signature -67062 0xFFFFFFFFFFFEFA0A for kext BrcmFirmwareRepo.kext
kext-dev-mode allowing invalid signature -67062 0xFFFFFFFFFFFEFA0A for kext ApplePS2Keyboard.kext
kext-dev-mode allowing invalid signature -67062 0xFFFFFFFFFFFEFA0A for kext ApplePS2Controller.kext
kext-dev-mode allowing invalid signature -67062 0xFFFFFFFFFFFEFA0A for kext ApplePS2SmartTouchPad.kext
kext-dev-mode allowing invalid signature -67013 0xFFFFFFFFFFFEFA3B for kext AppleMobileDevice.kext
kext-dev-mode allowing invalid signature -67030 0xFFFFFFFFFFFEFA2A for kext AppleHDA_ALC256.kext
```
Now you know why your brightness keys do not work.

My script never install kexts(expect AppleHDA_ALC256, CodecCommander, Brcm*) to system path.

syscl

**Comment by furrybanana** [comment]
well then this might be old data. I followed https://www.tonymacx86.com/threads/guide-dell-xps-13-9350-macos-10-12-1.204730/ before I found your git 
should I remove them all from /S/L/E manually?

thank you

**Comment by syscl** [comment]
@furrybanana right, I never use other guides to install my XPS 13. I use my own experience...

syscl

**Comment by furrybanana** [comment]
removing them now and deploying your script again, rebooting in hope to have it running.

**Comment by syscl** [comment]
@furrybanana Notice you should also remove all ACPI/origin/*.aml, then re dump it from your own XPS 13 under Clover by pressing F4/Fn+F4. Don't use ACPI tables other than yours.

syscl

**Comment by furrybanana** [comment]
so I don't seem to find any voodoo in /S/L/E - weird?
I did dump with F4 on boot in clover. this origin folder is what I got. don't know about the *.aml

easiest way to save my data, fresh install of macOS and restoring data? carbon copy ?

**Comment by syscl** [comment]
Check /Library/Extensions as well.

syscl

**Comment by furrybanana** [comment]
ok got it working but I have a lot of kext in there and some warnings in the debug again. I will reinstall the whole system. The apple/command key moved from the windows key to alt. will have to change that too ^^

thank you very much for your help. I will report further bugs and progress. I am new to macOS and theres a lot of mackintosh stuff I don't understand yet.

**Comment by syscl** [comment]
Congrats. This issue marked as solved/unrelated to deploy.sh. Not a deploy's bug.

Report new issue once you find.

Thank you,
syscl
