### ISSUE TITLE
9350 i5-6300 and auto-detect ig-platform-id

### ISSUE THREAD

**Issue by xrayos** [syscl/XPS9350-macOS#36]
syscl your script is great!

However, I does not auto-detect the i5-6300 chipset and it does not make any modifications to your config.plist. All that I did to get my system working was the following:

1. installed OS X via usb stick using your clover folder
2. installed clover and copied over your clover folder to the EFI partition on the internal ssd
3. executed your deploy.sh, but it did not make any changes to your original config.plist.
4. system works good though.
5. if I delete the config.plist and then run your deploy.sh it only creates a config.plist with the ALC256 patches, nothing else. 

Here's a debug screen dump via terminal. I just did a copy and paste.

[debug.docx](https://github.com/syscl/XPS9350-macOS/files/737260/debug.docx)

**Comment by syscl** [comment]
Why delete config.plist?? You need to use origin config.plist from my GitHub, then run deploy.sh

syscl

**Comment by syscl** [comment]
Give me your normal mode of executing, don't use -debug argument.

syscl

**Comment by xrayos** [comment]
I just deleted the config.plist just to see what your script would do if the plist was missing from the /efi/clover folder. I wanted to see if it would copy over from your XPS9350-macos folder.

anyhow, here's the output from normal deploy.sh. I've also included the config.plist in my /efi/clover folder after the script was executed

thanks
[normal deploy.docx](https://github.com/syscl/XPS9350-macOS/files/737303/normal.deploy.docx)
[config.plist.zip](https://github.com/syscl/XPS9350-macOS/files/737304/config.plist.zip)

**Comment by syscl** [comment]
Could you give me some information from terminal?

```sh
ioreg -lw0 |grep -i "Intel Iris Graphics" |sed -e "/[^<]*<\"/s///" -e "s/\"\>//"
```

syscl

**Comment by xrayos** [comment]
hmm, 

I've got no terminal output using that command

**Comment by syscl** [comment]
@xrayos Thank you, the problem doesn't lie here.

But I found out what's wrong due to you point out.

Thank you,
syscl

**Comment by syscl** [comment]
@xrayos Please try latest deploy.sh

syscl

**Comment by xrayos** [comment]
Just tried your new deploy.sh


same result. it kept your ig-platform-id the same, 0x19260004


I could just modify the config.plist afterwards. I'm just curious if there are any other dependencies that your script will execute if the graphics id is not correct for my system.

**Comment by syscl** [comment]
Just paste the execution of deploy.sh here, don't use docx.

syscl

**Comment by syscl** [comment]
@xrayos I saw another problem that cause ig-platform-id do not change, give me one second.

syscl

**Comment by syscl** [comment]
@xrayos Please try latest deploy.sh

syscl

**Comment by xrayos** [comment]
just executed your new deploy.sh 

here's the output. The script does figure out I have an i5-6300, but the config.plist keeps the ig-platform-id the same as your original



Hs-MacBook:XPS9350-macOS hlim$ ./deploy.sh
[ ---> ]  Updating files from https://github.com/syscl/XPS9350-macOS...
[ Note ]  https://github.com/syscl/XPS9350-macOS is not available at this time, please link https://github.com/syscl/XPS9350-macOS again next time..
[ Note ]  Your laptop is non-Iris version(i5-6300U).
[  OK  ]  Pre stage cleanup.
[  OK  ]  Create ./DSDT.
[  OK  ]  Create ./DSDT/prepare.
[  OK  ]  Create ./DSDT/precompile.
[  OK  ]  Create ./DSDT/compile.
/dev/disk0 (internal):
   #:                       TYPE NAME                    SIZE       IDENTIFIER
   0:      GUID_partition_scheme                         256.1 GB   disk0
   1:                        EFI EFI                     209.7 MB   disk0s1
   2:                  Apple_HFS xps                     119.5 GB   disk0s2
   3:                 Apple_Boot Recovery HD             650.0 MB   disk0s3
   4:                  Apple_HFS                         7.5 GB     disk0s4
   5:         Microsoft Reserved                         16.8 MB    disk0s5
   6:       Microsoft Basic Data win10                   127.6 GB   disk0s6
   7:           Windows Recovery                         471.9 MB   disk0s7

Enter EFI's IDENTIFIER, e.g. disk0s1: disk0s1
[  OK  ]  Mount disk0s1.
[  OK  ]  Copy untouch ACPI tables.
Available touchpad kext:

[  1  ] ApplePS2SmartTouchPad
[  2  ] VoodooPS2Controller.kext

Please choose the desired touchpad kext (1 or 2): 2
[ Note ]  Use VoodooPS2Controller.
[ ---> ]  Disassembling tables...
[  OK  ]  Disassemble DSDT.
[  OK  ]  Disassemble FACP.
[  OK  ]  Search specification tables by syscl/Yating Zhou.
[ ---> ]  Patching DSDT.dsl
[  OK  ]  Rename DSM.
[  OK  ]  Fix word field length Dword->Qword credit syscl.
[  OK  ]  OS Check Fix.
[  OK  ]  Fix brightness keys(F11/F12).
[  OK  ]  HDAS->HDEF.
[  OK  ]  Add audio Layout 1.
[  OK  ]  Rename GFX0 to IGPU.
[  OK  ]  Inject USBX and PNLF credit syscl.
[  OK  ]  Fix USB _PRW.
[  OK  ]  IRQ Fix.
[  OK  ]  SMBus Fix.
[  OK  ]  AC Adapter Fix.
[  OK  ]  Add MCHC.
[  OK  ]  Fix _WAK Arg0 v2.
[  OK  ]  Add IMEI.
[  OK  ]  Fix Non-zero Mutex.
[  OK  ]  Fix MDBG Error credit x4080, syscl.
[  OK  ]  PPMC and PMCR combine together credit syscl.
[  OK  ]  Insert DMAC(PNP0200).
[  OK  ]  Make Device(MATH) load correctly in macOS.
[  OK  ]  SBTN->SLPB with correct _STA 0x0B.
[  OK  ]  iGPU TPMX to MEM2.
[  OK  ]  IMTR->TIMR, _T_x->T_x.
[  OK  ]  PXSX2ARPT with _PWR fix.
[  OK  ]  Remove WMI(PNP0C14).
[  OK  ]  Inject SSD device property credit syscl.
[  OK  ]  Declare GTF0 method object credit syscl.
[  OK  ]  Inject NVMe power management properties credit Pike R. Alpha, syscl.
[  OK  ]  Remove _PWR, _PSW in PWRB(PNP0C0C).
[  OK  ]  Inject reg-ltrovr for IOPCIFamily::setLatencyTolerance setting ltrOffset for PCI devices successfully (c) syscl.
[  OK  ]  Fix shutdown become reboot issue.
[  OK  ]  Remove DSDT backup.
[ ---> ]  Patching SSDT-14.dsl
[  OK  ]  Rename DSM.
[  OK  ]  Rename GFX0 to IGPU.
[ ---> ]  Patching SSDT-5.dsl
[  OK  ]  Rename GFX0 to IGPU.
[  OK  ]  Rename DSM.
[  OK  ]  Fix PARSEOP_IF error credit syscl.
[ ---> ]  Fixing reboot issue
[  OK  ]  Fix reboot issue credit syscl.
[ ---> ]  Copying tables to precompile...
[  OK  ]  Copy tables to precompile.
[ ---> ]  Copying untouched tables to ./DSDT/compile...
[  OK  ]  Copy untouched tables to ./DSDT/compile.
[ ---> ]  Compiling tables...
[  OK  ]  Compiling DSDT.
[  OK  ]  Compile DptfTa.
[  OK  ]  Compile SaSsdt.
[  OK  ]  Compile sensrhub.
[ ---> ]  Copying SSDT-rmne.aml to ./DSDT/compile...
[  OK  ]  Copy SSDT-rmne.aml to ./DSDT/compile.
[ ---> ]  Installing SSDT-XPS13SKL.aml to ./DSDT/compile...
[  OK  ]  Copy SSDT-XPS13SKL.aml to ./DSDT/compile.
[  OK  ]  Clean dynamic SSDTs.
[  OK  ]  Drop SSDT-3.
[  OK  ]  Drop SSDT-6.
[  OK  ]  Create /Volumes/EFI/EFI/CLOVER/ACPI/patched.
[  OK  ]  Copy tables to /Volumes/EFI/EFI/CLOVER/ACPI/patched.
[ ---> ]  Updating kexts...
[  OK  ]  Remove pervious kexts in /Volumes/EFI/EFI/CLOVER/kexts/10.12.
[  OK  ]  Update kexts from ./CLOVER/kexts/10.12.
[  OK  ]  Update kexts from ./Kexts.
[  OK  ]  Install VoodooPS2Controller.
Password:
[  OK  ]  Remove /Volumes/EFI/EFI/CLOVER/kexts/10.12/BrcmPatchRAM2.kext.
[  OK  ]  Remove /System/Library/Extensions/BrcmFirmwareRepo.kext.
[  OK  ]  Remove /System/Library/Extensions/BrcmPatchRAM2.kext.
[  OK  ]  Install BrcmPatchRAM2.
[  OK  ]  Install BrcmFirmwareRepo.
[ ---> ]  Installing audio...
[  OK  ]  Install audio.
[  OK  ]  Generate configuration file of sleepwatcher launch daemon.
[  OK  ]  Generating script to unmount external devices before sleep (c) syscl/lighting/Yating Zhou.
[  OK  ]  Generate script to load RTWlanUSB upon sleep.
[ ---> ]  Installing external devices sleep patch...
[  OK  ]  Install sleepwatcher daemon.
[  OK  ]  Install configuration of sleepwatcher daemon.
[  OK  ]  Install sleep script.
[  OK  ]  Install wake script.
[  OK  ]  Fix the permissions of /etc/sysclusbfix.sleep.
[  OK  ]  Fix the permissions of /etc/sysclusbfix.wake.
[  OK  ]  Trigger startup service of syscl.usb.fix.
[  OK  ]  Clean up.
[ ---> ]  Rebuilding kernel extensions cache...
[  OK  ]  Rebuild kernel extensions cache.
[ Note ]  Congratulations! All operation has been completed.
[ Note ]  Reboot now. -syscl/lighting/Yating Zhou @PCBeta.

**Comment by xrayos** [comment]
^update

I had to git clone again. The ig-platform-id is now correct


Thanks!

**Comment by syscl** [comment]
@xrayos Nice to hear that, now we can close this issue.

syscl

**Comment by xrayos** [comment]
Thank you!

amazing script
