### ISSUE TITLE
Question : macOS 10.12.3 Update anyone?

### ISSUE THREAD

**Issue by x4080** [syscl/XPS9350-macOS#37]
Hi guys, anybody already using it ? any issues ?

**Comment by xrayos** [comment]
did just a fresh install with 10.12.3 and it works great.

**Comment by icedman** [comment]
no problem with combo update

**Comment by x4080** [comment]
Thanks I'll try it

**Comment by syscl** [comment]
No need combo update either. Just click update in Apple Store, that's it.

syscl

**Comment by x4080** [comment]
Update works flawlessly, using appstore update, I'll close it now
