### ISSUE TITLE
Question : Anybody successfully using iMessage?

### ISSUE THREAD

**Issue by x4080** [syscl/XPS9350-macOS#38]
I cannot make it works, with the guides already available, but I dont have mac serial number so, maybe that's the reason, anybody have success with this matter ?

**Comment by syscl** [comment]
@x4080 I succeeded on both M3800 and XPS 13.

What you need to do, is go to App Store, take a picture from System Report -> Hardware Overview. Two of the important information are: serial number and UUID. 

That's it,
syscl

**Comment by R1MnTnA** [comment]
This is the method I used. -  https://www.reddit.com/r/hackintosh/comments/2wohwn/getting_imessage_working_on_10102_generating/

**Comment by R1MnTnA** [comment]
Also here is another good link.- http://www.fitzweekly.com/2016/02/hackintosh-imessage-tutorial.html?m=1

**Comment by x4080** [comment]
Thanks @syscl and @R1MnTnA

**Comment by x4080** [comment]
@syscl, its by using the real mac right? Or use our hackintosh?

**Comment by syscl** [comment]
Use real mac's serial number and UUID then inject into hackintosh(config.plist->SMBIOS section) that's it.

syscl

**Comment by x4080** [comment]
I'll get the mac serial and will let you know
