### ISSUE TITLE
Keyboard

### ISSUE THREAD

**Issue by x4080** [syscl/XPS9350-macOS#4]
Hi SysCl, I was updating the keyboard using 4.7 beta 3 and the tap function is not working, must use ioio @boot to set it, but your keyboard kext is works out of the box, how did you change the tap function inside the kext? using plist?

And another thing, do you know how to make scroll slower? the scroll is very fast

**Comment by icedman** [comment]
x4080, would you mind sharing 4.7.3?
i could not download from osxlatitude even after registering.

slowing scroll down. in think..
HIDTrackpadScrollAccelLevel = 2
IntertialScrollLevel = 2

**Comment by x4080** [comment]
Hi, I cant seem attach the file via github, even its a .zip, I share using google drive : https://drive.google.com/open?id=0B_fQIbGTZBWYNFRCY09YdzlyV0E

I just download it from the website, since I'm on other computer

BTW I'm now using voodoo because have better scroll control

**Comment by icedman** [comment]
Thank you x4080.
Voodoo still has problem with brightness keys issues.

I shared the driver i'm using at tonymacx86 (https://www.tonymacx86.com/threads/guide-dell-xps-13-9350-macos-10-12-1.204730/page-40#post-1389848)

ApplePS2 4.6.5 frankensteined with 4.6.8. The scroll setting is adjusted already. but i could not make the 2Fingers > right click to work.

**Comment by x4080** [comment]
Cool

**Comment by syscl** [comment]
@icedman @x4080 try the latest update, I have merged azlvda, tdmsn's brightness key fix, now on my laptop it work like a charm.

Good luck,
syscl

**Comment by icedman** [comment]
syscl, thanks!
i've been using your scripts since your project in M3800/XPS9530.
and it looks like sierra is almost perfect now.

**Comment by x4080** [comment]
@syscl you re the man :)

**Comment by x4080** [comment]
@icedman , thunderbolt3 next?

**Comment by x4080** [comment]
Tried the new 4.7 beta 5, and the 2 finger tap is not right mouse click, can we change it?

**Comment by syscl** [comment]
2f tap is ok in beta5, and I used thunderbolt to charge my XPS 13 9350 everyday.

I want people to confirm if the HDMI/DP works or not...

syscl

**Comment by applesjgtl** [comment]
Thunderbolt charging works fabulously. I don't have the right cable to test display out, unfortunately. Tap is super annoying to me and trackpad settings are missing again. I thought this was fixed in latest VoodooHDA kext?

**Comment by x4080** [comment]
Im using usb c hub and after sleep it wont recognize all the item connected to the hub and thunderbolt section in about is empty, @syscl and @applesjgtl do you have thunderbolt in about ?

Im using beta 5 and 2finger tap is equal middle button click and right button click is 3finger tap, am I only who experienced this? 

Thanks

**Comment by applesjgtl** [comment]
No, thunderbolt is totally blank in About. It’s working for power because I’m guessing that’s at a firmware level. Does USB C work? I could test, I have plenty of C devices. Gimme a sec.

**Comment by applesjgtl** [comment]
By the way, when I close the laptop it doesn’t sleep. Screen remains on. Still having issues with resume upon reopening if I manually sleep the laptop.

**Comment by icedman** [comment]
2Finger = middle button.. same here.. could change even with editing plist.
i've gotten used to CTR + Tap for right click. not a problem any more :)

**Comment by x4080** [comment]
@icedman, it's not just me then, btw how do you make brightness key work?

maybe @syscl can help?

**Comment by x4080** [comment]
@applesjgtl sleep wake is working fine with me after tapping something with keyboard, close lid to sleep is not working though

**Comment by syscl** [comment]
@x4080 use latest deploy u will see brightness key work. btw do not forget to use latest config under my git

**Comment by icedman** [comment]
@x4080, i see syscl's patches for brightness keys are already in.  they should work with ApplePS2SmartTouchpad.  it worked for me with 4.6.8

**Comment by gctseng** [comment]
By "brightness keys" are we talking about changing the screen brightness?  Because mine doesn't work.  I don't even have any brightness slider in the control panel.  Also, do I need to copy any kexts into /S/L/E?  I don't see any of the kexts from the CLOVER directory or the repository in the SLE folder.  For example, the ApplePS2SmartTouchpad, which seems to be the important one.

Thanks for any advice.

**Comment by applesjgtl** [comment]
I'm not having any control over brightness using the actual brightness keys, they still seem to be mapped to command+b and command+s. But at least I can modify screen brightness!


On Tue, Dec 13, 2016 at 12:47pm, George Tseng < notifications@github.com [notifications@github.com] > wrote:
By "brightness keys" are we talking about changing the screen brightness? Because mine doesn't work. I don't even have any brightness slider in the control panel. Also, do I need to copy any kexts into /S/L/E? I don't see any of the kexts from the CLOVER directory or the repository in the SLE folder. For example, the ApplePS2SmartTouchpad, which seems to be the important one.

Thanks for any advice.

**Comment by x4080** [comment]
@applesjgtl , Command B and S is already in the Voodoo before, @syscl do the brightness key mean Fn F11  and Fn-F12? I already patch DSDT using your brightness fix

**Comment by icedman** [comment]
i just tested the latest voodoops2 1.8.25 now. all the proper keys work. volume, brightness. plus it has a smoother scroll.  less gestures though.

but the patch you need for the keys is different.
https://github.com/icedman/XPS13-9350-hackintosh/blob/master/patches/iceman/keyboard2.txt

if the pointer jumps all around the screen for you, you can build the kext yourself with patches:
https://github.com/icedman/XPS13-9350-hackintosh/tree/master/patches/VoodooPS2
or download my build:
http://kludgets.com/voodoops2.1.8.25.zip

**Comment by x4080** [comment]
@icedman , nice job, I confused to go back with voodoo with smoother scroll and not conflict with mouse wheel scroll or using appleps2 one with lot of gestures 

Maybe Voodoo can be improved like appleps2 and it will be perfect, do you know how to add more gestures recognition?

**Comment by icedman** [comment]
@x4080,  it is better we support voodoo as it is open source.  
there are some recent developments with voodoo in terms of features:

https://github.com/RehabMan/OS-X-Voodoo-PS2-Controller/network

tluck and usr-sse2's forks are for adding more gestures, including 3-finger drag like a real mac

**Comment by x4080** [comment]
Thanks @icedman

**Comment by x4080** [comment]
Quick tips for brightness, using keyboard shortcut menu, change brightness to F11 and F12 will solve the brightness problem, not using Fn F11 but directly F11 or F12

Hopefully it helps someone

**Comment by syscl** [comment]
@x4080 it's weird, now my F11 and F12 cannot work...

syscl

**Comment by gctseng** [comment]
When I press Fn-Insert the screen immediately goes blank and the computer eventually turns off. I then have to press the power button to turn it back on.  When I log back in, Firefox launches like that there was a crash (i.e., asking me if I want to reload the tabs with that message "This is embarrassing, Firefox seems to have crashed.").  What's the deal with that key?

Also confirm that Fn-PrtScr increases LCD brightness, F9 mutes (so does F1, which is expected), but F11 and F12 do not do anything but Fn-F11 clears the screen and Fn-F12 brings up the gadgets.  Can anyone explain?

I'm using whatever is in the repository, so I'm presuming its the ApplePS2SmartTouchpad.

One last odd thing is that after I installed my DW1830, my trackpad scrolling became super fast.

**Comment by syscl** [comment]
@x4080 @icedman @applesjgtl @gctseng Note: there seems some softwares will crash then reopen again, this is not our hardware issue, it's the Sierra! Sierra, one of the worst operating system I've used. Similar issue can be found in apple discussion [here](https://discussions.apple.com/thread/7687562?start=0&tstart=0). Before you open the link I just post, be peaceful, there will be 26 page long(too many)... What can I said cook? 5 yrs w/o Jobs is really a problem.

syscl

**Comment by x4080** [comment]
@syscl, Wanna try my appleps2 ?
[ApplePS2SmartTouchPad.kext.zip](https://github.com/syscl/XPS9350-macOS/files/659228/ApplePS2SmartTouchPad.kext.zip)

Im using this one and change the keyboard shortcut setting of brightness and it just works :)

10.12.2 seems not recognizing thunderbolt now, anybody can confirm? What changes is 10.12.2 and using latest deploy.sh from @syscl

**Comment by x4080** [comment]
@gctseng , try my appleps2, mine works fine

**Comment by syscl** [comment]
@x4080 No still no work. It's weird, I have made this work before. But now I don't know what's wrong...

syscl

**Comment by x4080** [comment]
@syscl , do you already change the keyboard shortcut settings and set brightness to F11 and F12? How about trackpad pref, is it not appear?

**Comment by syscl** [comment]
@x4080 I can set it to Fn+F11 and Fn+F12. But previous, I can use F11 and F12 directly without Fn...

It's weird. Trackpad pref appear using your version...

syscl

**Comment by x4080** [comment]
To use F11 and F12 directly, must use keyboard shortcut to map from f13/f14 (display section)

**Comment by syscl** [comment]
where can I map to F13/F14? Do you mean F14/F15?

**Comment by syscl** [comment]
Could u please post a screen shot about that section. My is F14 and F15

**Comment by x4080** [comment]
Sorry for f14 and f15

**Comment by gctseng** [comment]
@x4080 Thanks. Trackpad seems to be working well with your version of the kext.  I'll try to remap the keys later.  I wish Karabiner worked on Sierra...

**Comment by x4080** [comment]
@gctseng, cool, did you try the f14 f15 map?

**Comment by gctseng** [comment]
@x4080 @syscl There is a "Shortcuts" tab in the Keyboard pref pane and, under El Capitan I can see a "Display" entry where I can check the F14/F15 entries. However, I don't see one in Sierra. This may or may not be related, but when I go to the Displays pref pane, I notice a couple of unset values.  Look at the title and the Refresh Rate:
![screen shot 2016-12-19 at 10 57 25 am](https://cloud.githubusercontent.com/assets/7102506/21325443/3f7dbcca-c5db-11e6-9b2d-b009d6e15c7b.png)

**Comment by syscl** [comment]
F11/F12 brightness keys function has been fixed already.
