### ISSUE TITLE
xps 9350 late 2015 

### ISSUE THREAD

**Issue by arbitary** [syscl/XPS9350-macOS#41]
My Dell xps 9350 is the late 2015 version. I couldn't get the Dell Wireless 1820A WiFi adapter working.

**Comment by syscl** [comment]
Hi @arbitary 

DW 1820A cannot open correctly on XPS 13 9350, though it can be powered up on M3800.

In theory you can find binary patch to make it work, but I just want my life simple, thus I swap to DW1830.

syscl

**Comment by arbitary** [comment]
Any suggestion where I can buy the DW1830 card? I can't find it on Amazon.

**Comment by syscl** [comment]
@arbitary eBay

syscl
