### ISSUE TITLE
Kernel Panic with SSDT-pr

### ISSUE THREAD

**Issue by squash-** [syscl/XPS9350-macOS#47]
I get a kernel panic whenever I use the included SSDT-pr, generate one using Pikeralpha's SsdtPRGen, or if I have clover generate C-States and P-States.

I've attached a picture of the panic and my clover folder.
[Clover.zip](https://github.com/syscl/XPS9350-macOS/files/755343/Clover.zip)
![img_0893](https://cloud.githubusercontent.com/assets/740545/22657887/073582e2-ec66-11e6-97df-18be80873569.JPG)

**Comment by Nomad347** [comment]
answer is here.
https://github.com/syscl/XPS9350-macOS/issues/31
You need frequency vectors from piker

**Comment by squash-** [comment]
@Nomad347 So I have to set the frequency vectors before using SSDT-pr.aml?

**Comment by Nomad347** [comment]
Yes. And use both.  SSDT-pr.aml  and freq vest. Then drop the clover generate c and p states

**Comment by squash-** [comment]
@Nomad347 @syscl Cool. I got it to boot with SSDT-pr.aml without a panic now.

The only issue that I have now is that it power usage doesn't drop below 1.75 watts although CPU clockspeed is around 500MHz idle.

Any of you run into this issue?

I've tried other freqvectors but anything other than MacBookPro11,1/11,2 the clock speed doesn't go under 1.3GHz.

**Comment by syscl** [comment]
@squash- I use MacBookPro11,2 which gives me the best temperature around 49°C and 6~8 hours battery life. Pretty sweet.

syscl

**Comment by squash-** [comment]
@syscl I'm using MacBookPro11,2 as well and get around those temps and battery life. So I guess it's a non issue. Just interesting that I don't go below 1.7W power usage when you and Nomad posted screenshots of lower. Anyway. This is great and thanks for this amazing script!

**Comment by syscl** [comment]
@squash- Disable SD-Card in BIOS, you will see the power consume lower down.

syscl

**Comment by squash-** [comment]
@syscl SD-Card is already disabled. So IDK what else it could be. But as it stands I'm getting pretty good battery life. So I'll investigate if it degrades or something in the near future. Thanks again.

**Comment by syscl** [comment]
@squash- Thank you!

syscl
