### ISSUE TITLE
Warning!! DSDT and SSDTs doesn't exist!

### ISSUE THREAD

**Issue by Fred33000** [syscl/XPS9350-macOS#48]
Hi,

i have a problem with the script.

this is what I have in the terminal

Last login: Mon Feb  6 17:02:33 on console
freds-macbook:~ fred$ git clone https://github.com/syscl/XPS9350-macOS
xcode-select: note: no developer tools were found at '/Applications/Xcode.app', requesting install. Choose an option in the dialog to download the command line developer tools.
freds-macbook:~ fred$ git clone https://github.com/syscl/XPS9350-macOS
Cloning into 'XPS9350-macOS'...
remote: Counting objects: 1336, done.
remote: Compressing objects: 100% (27/27), done.
remote: Total 1336 (delta 9), reused 0 (delta 0), pack-reused 1309
Receiving objects: 100% (1336/1336), 8.46 MiB | 3.66 MiB/s, done.
Resolving deltas: 100% (480/480), done.
freds-macbook:~ fred$ cd XPS9350-macOS/
freds-macbook:XPS9350-macOS fred$ chmod +x ./deploy.sh
freds-macbook:XPS9350-macOS fred$ ./deploy.sh   **_(I made the same with SUDO and same issue)_**
[ ---> ]  Updating files from https://github.com/syscl/XPS9350-macOS...
Already up-to-date.
[ Note ]  Your laptop is non-Iris version(i7-6500U).
[  OK  ]  Pre stage cleanup.
[  OK  ]  Create ./DSDT.
[  OK  ]  Create ./DSDT/prepare.
[  OK  ]  Create ./DSDT/precompile.
[  OK  ]  Create ./DSDT/compile.
/dev/disk0 (internal):
   #:                       TYPE NAME                    SIZE       IDENTIFIER
   0:      GUID_partition_scheme                         512.1 GB   disk0
   1:                        EFI EFI                     209.7 MB   disk0s1
   2:          Apple_CoreStorage Sans titre              511.3 GB   disk0s2
   3:                 Apple_Boot Recovery HD             650.0 MB   disk0s3

/dev/disk1 (internal, virtual):
   #:                       TYPE NAME                    SIZE       IDENTIFIER
   0:                            Sans titre             +510.9 GB   disk1
                                 Logical Volume on disk0s2
                                 6A638583-90B3-4E84-951E-7ADEE085C1A3
                                 Unencrypted

Enter EFI's IDENTIFIER, e.g. disk0s1: 
[FAILED]  Mount. **(I can mount the /volume/efi in command line)**
Usage:   diskutil mount [readOnly] [-mountPoint Path] DiskIdentifier|DeviceNode
Mount will mount the volume in the "standard" place (/Volumes), unless
an optional mount point is specified.
Set: Entry, ":Graphics:Inject:Intel", Does Not Exist
[ Note ]  Warning!! DSDT and SSDTs doesn't exist! Press Fn+F4 under Clover to dump ACPI tables.

Any help can be great.

Thank you 

Fred

**Comment by furrybanana** [comment]
Hi there,

[ Note ] Warning!! DSDT and SSDTs doesn't exist! Press Fn+F4 under Clover to dump ACPI tables.

means you have to create those file before you run the script. How to do it:
Reboot your machine, when you are seeing the CLOVER screen with your MacOS and Recovery Partition, use your arrow keys to mark the MacOS partition and then press F4 - wait 5 seconds, then boot to the system. 
Run ./Deploy.sh
select disk0s1
select Trackpad driver (0 or 1)
Reboot.

**Comment by Fred33000** [comment]
Thanks for your reply !

i had to made 2 times the F4 with reboot.

and I made manual the mount


Enter EFI's IDENTIFIER, e.g. disk0s1: 
[FAILED]  Mount.
Usage:   diskutil mount [readOnly] [-mountPoint Path] DiskIdentifier|DeviceNode
Mount will mount the volume in the "standard" place (/Volumes), unless
an optional mount point is specified.
[ Note ]  Warning!! DSDT and SSDTs doesn't exist! Press Fn+F4 under Clover to dump ACPI tables.
freds-macbook:XPS9350-macOS fred$ sudo mkdir /Volumes/EFI
freds-macbook:XPS9350-macOS fred$ sudo mount -t msdos /dev/disk0s1 /Volumes/efi
freds-macbook:XPS9350-macOS fred$ sudo ./deploy.sh
[ ---> ]  Updating files from https://github.com/syscl/XPS9350-macOS...
Already up-to-date.
[ Note ]  Your laptop is non-Iris version(i7-6500U).
[  OK  ]  Pre stage cleanup.
[  OK  ]  Create ./DSDT.
[  OK  ]  Create ./DSDT/prepare.
[  OK  ]  Create ./DSDT/precompile.
[  OK  ]  Create ./DSDT/compile.
/dev/disk0 (internal):
   #:                       TYPE NAME                    SIZE       IDENTIFIER
   0:      GUID_partition_scheme                         512.1 GB   disk0
   1:                        EFI EFI                     209.7 MB   disk0s1
   2:          Apple_CoreStorage Sans titre              511.3 GB   disk0s2
   3:                 Apple_Boot Recovery HD             650.0 MB   disk0s3

/dev/disk1 (internal, virtual):
   #:                       TYPE NAME                    SIZE       IDENTIFIER
   0:                            Sans titre             +510.9 GB   disk1
                                 Logical Volume on disk0s2
                                 6A638583-90B3-4E84-951E-7ADEE085C1A3
                                 Unencrypted

Enter EFI's IDENTIFIER, e.g. disk0s1: 
[FAILED]  Mount.
Usage:   diskutil mount [readOnly] [-mountPoint Path] DiskIdentifier|DeviceNode
Mount will mount the volume in the "standard" place (/Volumes), unless
an optional mount point is specified.
[  OK  ]  Copy untouch ACPI tables.
Available touchpad kext:

[  1  ] ApplePS2SmartTouchPad
[  2  ] VoodooPS2Controller.kext

Please choose the desired touchpad kext (1 or 2): 2
[ Note ]  Use VoodooPS2Controller.
[ ---> ]  Disassembling tables...
[  OK  ]  Disassemble DSDT.
[  OK  ]  Disassemble FACP.
[  OK  ]  Search specification tables by syscl/Yating Zhou.
[ ---> ]  Patching DSDT.dsl
[  OK  ]  _DSM->XDSM.
[  OK  ]  Fix word field length Dword->Qword credit syscl.
[  OK  ]  OS Check Fix.
[  OK  ]  Fix brightness keys(F11/F12).
[  OK  ]  HDAS->HDEF.
[  OK  ]  Inject Audio Info.
[  OK  ]  Rename GFX0 to IGPU.
[  OK  ]  Inject USBX and PNLF credit syscl.
[  OK  ]  Fix USB _PRW.
[  OK  ]  IRQ Fix.
[  OK  ]  SMBus Fix.
[  OK  ]  AC Adapter Fix.
[  OK  ]  Add MCHC.
[  OK  ]  Fix _WAK Arg0 v2.
[  OK  ]  Add IMEI.
[  OK  ]  Fix Non-zero Mutex.
[  OK  ]  Fix MDBG Error credit x4080, syscl.
[  OK  ]  PPMC and PMCR combine together credit syscl.
[  OK  ]  Insert DMAC(PNP0200).
[  OK  ]  Make Device(MATH) load correctly in macOS.
[  OK  ]  SBTN->SLPB with correct _STA 0x0B.
[  OK  ]  iGPU TPMX to MEM2.
[  OK  ]  IMTR->TIMR, _T_x->T_x.
[  OK  ]  PXSX2ARPT with _PWR fix.
[  OK  ]  Remove WMI(PNP0C14).
[  OK  ]  Inject SSD device property credit syscl.
[  OK  ]  Declare GTF0 method object credit syscl.
[  OK  ]  Inject NVMe power management properties credit Pike R. Alpha, syscl.
[  OK  ]  Remove _PWR, _PSW in PWRB(PNP0C0C).
[  OK  ]  Inject reg-ltrovr for IOPCIFamily::setLatencyTolerance setting ltrOffset for PCI devices successfully (c) syscl.
[  OK  ]  Fix shutdown become reboot issue.
[  OK  ]  Remove DSDT backup.
[ ---> ]  Patching SSDT-14.dsl
[  OK  ]  Rename GFX0 to IGPU.
[ ---> ]  Patching SSDT-5.dsl
[  OK  ]  _DSM->XDSM.
[  OK  ]  Rename GFX0 to IGPU.
[  OK  ]  _DSM->XDSM.
[  OK  ]  Fix PARSEOP_IF error credit syscl.
[ ---> ]  Fixing reboot issue
[  OK  ]  Fix reboot issue credit syscl.
[ ---> ]  Copying tables to precompile...
[  OK  ]  Copy tables to precompile.
[ ---> ]  Copying untouched tables to ./DSDT/compile...
[  OK  ]  Copy untouched tables to ./DSDT/compile.
[ ---> ]  Compiling tables...
[  OK  ]  Compiling DSDT.
[  OK  ]  Compile DptfTa.
[  OK  ]  Compile SaSsdt.
[  OK  ]  Compile sensrhub.
[ ---> ]  Copying SSDT-rmne.aml to ./DSDT/compile...
[  OK  ]  Copy SSDT-rmne.aml to ./DSDT/compile.
[ ---> ]  Installing SSDT-XPS13SKL.aml to ./DSDT/compile...
[  OK  ]  Install SsdtS3 table.
[ ---> ]  Installing SSDT-ARPT-RP05.aml to ./DSDT/compile...
[  OK  ]  Install ARPT table.
[  OK  ]  Clean dynamic SSDTs.
[  OK  ]  Drop SSDT-3.
[  OK  ]  Drop SSDT-6.
[  OK  ]  Create /Volumes/EFI/EFI/CLOVER/ACPI/patched.
[  OK  ]  Copy tables to /Volumes/EFI/EFI/CLOVER/ACPI/patched.
[ ---> ]  Updating kexts...
[  OK  ]  Remove pervious kexts in /Volumes/EFI/EFI/CLOVER/kexts/10.12.
[  OK  ]  Update kexts from ./CLOVER/kexts/10.12.
[  OK  ]  Update kexts from ./Kexts.
[  OK  ]  Install VoodooPS2Controller.
[  OK  ]  Remove /Volumes/EFI/EFI/CLOVER/kexts/10.12/BrcmPatchRAM2.kext.
[  OK  ]  Install BrcmPatchRAM2.
[  OK  ]  Install BrcmFirmwareRepo.
[ ---> ]  Installing audio...
[  OK  ]  Install audio.
[ ---> ]  Unlocking maximum pixel clock...
[  OK  ]  Patch and sign framework.
[  OK  ]  Generate configuration file of sleepwatcher launch daemon.
[  OK  ]  Generating script to unmount external devices before sleep (c) syscl/lighting/Yating Zhou.
[  OK  ]  Generate script to load RTWlanUSB upon sleep.
[ ---> ]  Installing external devices sleep patch...
[  OK  ]  Install sleepwatcher daemon.
[  OK  ]  Install configuration of sleepwatcher daemon.
[  OK  ]  Install sleep script.
[  OK  ]  Install wake script.
[  OK  ]  Fix the permissions of /etc/sysclusbfix.sleep.
[  OK  ]  Fix the permissions of /etc/sysclusbfix.wake.
[  OK  ]  Trigger startup service of syscl.usb.fix.
[  OK  ]  Clean up.
[  OK  ]  Change hibernatemode from 3 to 0.
[  OK  ]  Mount disk0s3.
[  OK  ]  Create /tmp/RecoveryHD.
[  OK  ]  Create /Users/fred/XPS9350-macOS/Backups/2017-02-07-h13_38_12.
[ ---> ]  Convert UDZO(r/o) to UDRW(r/w) ...
[  OK  ]  Convert UDZO(r/o) to UDRW(r/w).
[  OK  ]  Attach Recovery HD.
[  OK  ]  Patch and sign framework for Recovery HD.
[  OK  ]  Detach mountpoint.
[ ---> ]  Convert UDRW(r/w) to UDZO(r/o) ...
[  OK  ]  Convert UDRW(r/w) to UDZO(r/o).
[ ---> ]  Updating Recovery HD for DELL XPS 13 9350...
[  OK  ]  Clean redundant dmg files.
[  OK  ]  Unmount disk0s3.
[ ---> ]  Rebuilding kernel extensions cache...
[  OK  ]  Rebuild kernel extensions cache.
[  OK  ]  Remove /Volumes/EFI/EFI/CLOVER/config.plistg.
[ Note ]  Congratulations! All operation has been completed.
[ Note ]  Reboot now. -syscl/lighting/Yating Zhou @PCBeta.
freds-macbook:XPS9350-macOS fred$ 

my original problem is solved !

thank you

now I have to verify why I don't have the wifi

Fred

**Comment by furrybanana** [comment]
Which wifi card do you use? Would be nice if you could post your Dell XPS specs (CPU, SSD, Screen, Wifi-Chip)
If it's a Dell 1820A I am sorry I don't know how to patch it. 
I used the Dell 1830 recommended by @syscl because it works out of the box with macOS and Linux.

**Comment by syscl** [comment]
@Fred33000 where's your disk identifier? You type in nothing right? You need to type in disk0s1, otherwise, deploy don't know which EFI you want to mount and patch.

syscl

**Comment by Fred33000** [comment]
@furrybanana Thx yes it's DW1820A

i have a 

i7-6500u 
16Gb 
QUHD
512Gb Samsung 950Pro
DW1820A

thx again for your help.

**Comment by Fred33000** [comment]
@syscl yes you are completely right. I was thinking just enter was enough (like just enter if is ok)




i have always the problem due the version of my wireless card. I need to purchase a 1830 ?

thank you

Fred


freds-macbook:XPS9350-macOS fred$ sudo ./deploy.sh
[ ---> ]  Updating files from https://github.com/syscl/XPS9350-macOS...
Already up-to-date.
[ Note ]  Your laptop is non-Iris version(i7-6500U).
[  OK  ]  Pre stage cleanup.
[  OK  ]  Create ./DSDT.
[  OK  ]  Create ./DSDT/prepare.
[  OK  ]  Create ./DSDT/precompile.
[  OK  ]  Create ./DSDT/compile.
/dev/disk0 (internal):
   #:                       TYPE NAME                    SIZE       IDENTIFIER
   0:      GUID_partition_scheme                         512.1 GB   disk0
   1:                        EFI EFI                     209.7 MB   disk0s1
   2:          Apple_CoreStorage Sans titre              511.3 GB   disk0s2
   3:                 Apple_Boot Recovery HD             650.0 MB   disk0s3

/dev/disk1 (internal, virtual):
   #:                       TYPE NAME                    SIZE       IDENTIFIER
   0:                            Sans titre             +510.9 GB   disk1
                                 Logical Volume on disk0s2
                                 6A638583-90B3-4E84-951E-7ADEE085C1A3
                                 Unencrypted

Enter EFI's IDENTIFIER, e.g. disk0s1: disk0s1
[  OK  ]  Mount disk0s1.
[  OK  ]  Copy untouch ACPI tables.
Available touchpad kext:

[  1  ] ApplePS2SmartTouchPad
[  2  ] VoodooPS2Controller.kext

Please choose the desired touchpad kext (1 or 2): 2
[ Note ]  Use VoodooPS2Controller.
[ ---> ]  Disassembling tables...
[  OK  ]  Disassemble DSDT.
[  OK  ]  Disassemble FACP.
[  OK  ]  Search specification tables by syscl/Yating Zhou.
[ ---> ]  Patching DSDT.dsl
[  OK  ]  _DSM->XDSM.
[  OK  ]  Fix word field length Dword->Qword credit syscl.
[  OK  ]  OS Check Fix.
[  OK  ]  Fix brightness keys(F11/F12).
[  OK  ]  HDAS->HDEF.
[  OK  ]  Inject Audio Info.
[  OK  ]  Rename GFX0 to IGPU.
[  OK  ]  Inject USBX and PNLF credit syscl.
[  OK  ]  Fix USB _PRW.
[  OK  ]  IRQ Fix.
[  OK  ]  SMBus Fix.
[  OK  ]  AC Adapter Fix.
[  OK  ]  Add MCHC.
[  OK  ]  Fix _WAK Arg0 v2.
[  OK  ]  Add IMEI.
[  OK  ]  Fix Non-zero Mutex.
[  OK  ]  Fix MDBG Error credit x4080, syscl.
[  OK  ]  PPMC and PMCR combine together credit syscl.
[  OK  ]  Insert DMAC(PNP0200).
[  OK  ]  Make Device(MATH) load correctly in macOS.
[  OK  ]  SBTN->SLPB with correct _STA 0x0B.
[  OK  ]  iGPU TPMX to MEM2.
[  OK  ]  IMTR->TIMR, _T_x->T_x.
[  OK  ]  PXSX2ARPT with _PWR fix.
[  OK  ]  Remove WMI(PNP0C14).
[  OK  ]  Inject SSD device property credit syscl.
[  OK  ]  Declare GTF0 method object credit syscl.
[  OK  ]  Inject NVMe power management properties credit Pike R. Alpha, syscl.
[  OK  ]  Remove _PWR, _PSW in PWRB(PNP0C0C).
[  OK  ]  Inject reg-ltrovr for IOPCIFamily::setLatencyTolerance setting ltrOffset for PCI devices successfully (c) syscl.
[  OK  ]  Fix shutdown become reboot issue.
[  OK  ]  Remove DSDT backup.
[ ---> ]  Patching SSDT-14.dsl
[  OK  ]  Rename GFX0 to IGPU.
[ ---> ]  Patching SSDT-5.dsl
[  OK  ]  _DSM->XDSM.
[  OK  ]  Rename GFX0 to IGPU.
[  OK  ]  _DSM->XDSM.
[  OK  ]  Fix PARSEOP_IF error credit syscl.
[ ---> ]  Fixing reboot issue
[  OK  ]  Fix reboot issue credit syscl.
[ ---> ]  Copying tables to precompile...
[  OK  ]  Copy tables to precompile.
[ ---> ]  Copying untouched tables to ./DSDT/compile...
[  OK  ]  Copy untouched tables to ./DSDT/compile.
[ ---> ]  Compiling tables...
[  OK  ]  Compiling DSDT.
[  OK  ]  Compile DptfTa.
[  OK  ]  Compile SaSsdt.
[  OK  ]  Compile sensrhub.
[ ---> ]  Copying SSDT-rmne.aml to ./DSDT/compile...
[  OK  ]  Copy SSDT-rmne.aml to ./DSDT/compile.
[ ---> ]  Installing SSDT-XPS13SKL.aml to ./DSDT/compile...
[  OK  ]  Install SsdtS3 table.
[ ---> ]  Installing SSDT-ARPT-RP05.aml to ./DSDT/compile...
[  OK  ]  Install ARPT table.
[  OK  ]  Clean dynamic SSDTs.
[  OK  ]  Drop SSDT-3.
[  OK  ]  Drop SSDT-6.
[  OK  ]  Create /Volumes/EFI/EFI/CLOVER/ACPI/patched.
[  OK  ]  Copy tables to /Volumes/EFI/EFI/CLOVER/ACPI/patched.
[ ---> ]  Updating kexts...
[  OK  ]  Remove pervious kexts in /Volumes/EFI/EFI/CLOVER/kexts/10.12.
[  OK  ]  Update kexts from ./CLOVER/kexts/10.12.
[  OK  ]  Update kexts from ./Kexts.
[  OK  ]  Install VoodooPS2Controller.
[  OK  ]  Remove /Volumes/EFI/EFI/CLOVER/kexts/10.12/BrcmPatchRAM2.kext.
[  OK  ]  Remove /System/Library/Extensions/BrcmFirmwareRepo.kext.
[  OK  ]  Remove /System/Library/Extensions/BrcmPatchRAM2.kext.
[  OK  ]  Install BrcmPatchRAM2.
[  OK  ]  Install BrcmFirmwareRepo.
[ ---> ]  Installing audio...
[  OK  ]  Install audio.
[ ---> ]  Unlocking maximum pixel clock...
[  OK  ]  Patch and sign framework.
[  OK  ]  Generate configuration file of sleepwatcher launch daemon.
[  OK  ]  Generating script to unmount external devices before sleep (c) syscl/lighting/Yating Zhou.
[  OK  ]  Generate script to load RTWlanUSB upon sleep.
[ ---> ]  Installing external devices sleep patch...
[  OK  ]  Install sleepwatcher daemon.
[  OK  ]  Install configuration of sleepwatcher daemon.
[  OK  ]  Install sleep script.
[  OK  ]  Install wake script.
[  OK  ]  Fix the permissions of /etc/sysclusbfix.sleep.
[  OK  ]  Fix the permissions of /etc/sysclusbfix.wake.
[  OK  ]  Trigger startup service of syscl.usb.fix.
[  OK  ]  Clean up.
[  OK  ]  Mount disk0s3.
[  OK  ]  Create /tmp/RecoveryHD.
[  OK  ]  Create /Users/fred/XPS9350-macOS/Backups/2017-02-07-h16_22_40.
[ ---> ]  Convert UDZO(r/o) to UDRW(r/w) ...
[  OK  ]  Convert UDZO(r/o) to UDRW(r/w).
[  OK  ]  Attach Recovery HD.
[  OK  ]  Patch and sign framework for Recovery HD.
[  OK  ]  Detach mountpoint.
[ ---> ]  Convert UDRW(r/w) to UDZO(r/o) ...
[  OK  ]  Convert UDRW(r/w) to UDZO(r/o).
[ ---> ]  Updating Recovery HD for DELL XPS 13 9350...
[  OK  ]  Clean redundant dmg files.
[  OK  ]  Unmount disk0s3.
[ ---> ]  Rebuilding kernel extensions cache...
[  OK  ]  Rebuild kernel extensions cache.
[ Note ]  Congratulations! All operation has been completed.
[ Note ]  Reboot now. -syscl/lighting/Yating Zhou @PCBeta.
freds-macbook:XPS9350-macOS fred$

**Comment by syscl** [comment]
@Fred33000 Yes, you need to buy DW 1560 or DW 1830. DW 1820 cannot be powered up correctly on XPS 13 9350. Though in theory, you can find out the binary patch for it. But I just want my life be simple thus I switch to better performance DW 1830, and yes, this card can be powered up by macOS natively.

syscl

**Comment by furrybanana** [comment]
The 1830 is around 25-30 bucks on eBay. 

Guide to install it:
https://www.ifixit.com/Guide/Dell+XPS+13+Wireless+Card+Replacement/76062

First time the backplate sits tight and the edges are sharp. I f'd up my fingers because I used my nails as a second plectrum - so better get 2 plastic items to open it ^^
