### ISSUE TITLE
Is the FakePCIID_Intel_HD_Graphics.kext still needed?

### ISSUE THREAD

**Issue by x4080** [syscl/XPS9350-macOS#5]
Is the FakePCIID_Intel_HD_Graphics.kext still needed?

**Comment by applesjgtl** [comment]
I'm not using it on Sierra / 12.2 beta 7 and it seems pretty rock solid. I think Apple's latest Skylake updates are helping quite a bit.

**Comment by x4080** [comment]
@applesjgtl , yeah me too

**Comment by syscl** [comment]
@x4080 No, I removed the ```FakePCIID_Intel_HD_Graphics.kext```. In 10.12.0, it's use to fix a safari bug... But seems in 10.12.1 and later the bug fix.


syscl

**Comment by x4080** [comment]
Cool
