### ISSUE TITLE
Can't reboot into masosx installed drive

### ISSUE THREAD

**Issue by pepi2810** [syscl/XPS9350-macOS#51]
So after a couple of hours I was finally able to get to installing OSX. I got all the way to the desktop and followed all the instructions. Upon reboot I could no longer boot into the drive. I switched the clover folder of the internal hard drive after installing clover to it with the same settings I did to the USB. Then I ran the script and still no luck in being able to boot after installing successfully.
 

This is a picture of what happens when I try booting into the macOSX drive
http://i.imgur.com/gU3u59Q.jpg

Xps 13 9350 128gb m.2 drive 8gb ram 1.6k MHz intel 520 and i5 6200U

If you could help me out I would really really appreciate it.
Thanks

**Comment by syscl** [comment]
Hi @pepi2810 

Do you use my Clover folder directory? Don't use RehabMan's latest FakeSMC, it will panic your system.

syscl

**Comment by pepi2810** [comment]
@syscl

Yes I used your Clover folder and switched it with the one on the flash drive and mac OSX efi after installation. I used rehabman's Kext for unsupportedsata drives so that my m.2 drive would show up. Without unsupportedsata kext my m.2 drive won't show. I will re do the installation and tell you everything I did in better detail. 

Thanks for helping me btw

**Comment by pepi2810** [comment]
@syscl

Ok so I did everything over again and now if I have the removable disk I can boot into macOSX 

I tried running the deploy.sh but it keeps telling me I don't have the DSDT and SSDT even though I can see the folder full of things because I did hit F4 and fn+f4 to make sure I dumped the tables. 

My questions would be how do I fix the deploy.sh and should I install clover with the same settings to the internal drive with OSX on it?

Thanks

**Comment by pepi2810** [comment]
@syscl

I forgot to mention that my wifi doesn't work either

Thanks

**Comment by syscl** [comment]
Hi @pepi2810 

DW 1820 will not work. Better switch to DW 1830 or DW 1560.

Show me your deploy.sh log.

syscl

**Comment by pepi2810** [comment]
This is my log for deploy.sh
http://i.imgur.com/Z2c4P2r.jpg


And for the wifi does this card work?
https://www.amazon.com/dp/B00JY6X9HM/ref=cm_sw_r_cp_api_I3iNyb8FVCNGK

And do I install clover with the same setting and switch the clover folder with yours on the actual macOSX ssd?

**Comment by syscl** [comment]
@pepi2810 You don't press Fn+F4 or F4 under Clover, that's why deploy throw this exception to you.

Show me more detail
```sh
diskutil mount disk0s1
ls -l /Volumes/EFI/Clover/ACPI/origin
```

Thank you,
syscl

**Comment by pepi2810** [comment]
@syscl

Finally I got it to work. 

The only thing is the wifi doesn't work is the card I linked good or no?

https://www.amazon.com/dp/B00JY6X9HM/ref=cm_sw_r_cp_api_I3iNyb8FVCNGK

**Comment by squash-** [comment]
@pepi2810 you need a m.2 half height pcie wifi card. something like this http://www.ebay.com/itm/371850825922 or the DW1560

**Comment by pepi2810** [comment]
@squash- 
@syscl 
thanks for the advice I'd prefer to buy the card on amazon

https://www.amazon.com/BCM94352Z-NGFF-WiFi-Bluetooth-802-11ac/dp/B00JGFA50U/ref=sr_1_2?s=pc&ie=UTF8&qid=1486670804&sr=1-2&keywords=dw1560

https://www.amazon.com/7260NGW-Intel-Wireless-AC-802-11ac-Bluetooth/dp/B00GUNZUG0/ref=sr_1_4?s=pc&ie=UTF8&qid=1486670804&sr=1-4&keywords=dw1560

Which one of those should I get and have it work with MaxOSX sierra

thanks

**Comment by syscl** [comment]
FYI, @pepi2810 Intel will not work...

syscl

**Comment by pepi2810** [comment]
@syscl 
oh ok thanks I will get the Broadcom one then
