### ISSUE TITLE
 [FAILED] i7-6600U Generate C-States and P-State

### ISSUE THREAD

**Issue by ZombieTheBest** [syscl/XPS9350-macOS#54]
Hi! 
Deploy script gives me that error as it can't find any CpuPm-i7-6600U.aml file. I think that this is related with CPU Power Managment, so i guess i have to do something about this, right? :)

Thank you!

**Comment by syscl** [comment]
@ZombieTheBest Could you please provide all the executing result of deploy.sh here?

Like:
```sh
/dev/disk0 (internal):
   #:                       TYPE NAME                    SIZE       IDENTIFIER
   0:      GUID_partition_scheme                         1.0 TB     disk0
   1:                        EFI EFI                     209.7 MB   disk0s1
   2:         Microsoft Reserved                         134.2 MB   disk0s2
   3:       Microsoft Basic Data OS                      276.6 GB   disk0s3
   4:                  Apple_HFS Macintosh HD            746.6 GB   disk0s4
   5:                 Apple_Boot Recovery HD             650.0 MB   disk0s5

Enter EFI's IDENTIFIER, e.g. disk0s1: 
...
```

Thank you,
syscl

**Comment by ZombieTheBest** [comment]
Sure, here you are :D 

> Mircos-MacBook:XPS9350-macOS-master mirco$ sudo ./Deploy.sh
> Password:
> [ ---> ]  Updating files from https://github.com/syscl/XPS9350-macOS...
> fatal: Not a git repository (or any of the parent directories): .git
> [ Note ]  Your laptop is non-Iris version(i7-6600U).
> [  OK  ]  Pre stage cleanup.
> [  OK  ]  Create ./DSDT.
> [  OK  ]  Create ./DSDT/prepare.
> [  OK  ]  Create ./DSDT/precompile.
> [  OK  ]  Create ./DSDT/compile.
> /dev/disk0 (internal):
>    #:                       TYPE NAME                    SIZE       IDENTIFIER
>    0:      GUID_partition_scheme                         256.1 GB   disk0
>    1:                        EFI EFI                     209.7 MB   disk0s1
>    2:          Apple_CoreStorage MacOS                   255.2 GB   disk0s2
>    3:                 Apple_Boot Recovery HD             650.0 MB   disk0s3
> 
> /dev/disk1 (internal, virtual):
>    #:                       TYPE NAME                    SIZE       IDENTIFIER
>    0:                            MacOS                  +254.8 GB   disk1
>                                  Logical Volume on disk0s2
>                                  C4C4B0F0-A5B7-43D0-AB75-49F2E98A1B23
>                                  Unencrypted
> 
> Enter EFI's IDENTIFIER, e.g. disk0s1: disk0s1
> [  OK  ]  Mount disk0s1.
> [  OK  ]  Copy untouch ACPI tables.
> Available touchpad kext:
> 
> [  1  ] ApplePS2SmartTouchPad
> [  2  ] VoodooPS2Controller.kext
> 
> Please choose the desired touchpad kext (1 or 2): 2
> [ Note ]  Use VoodooPS2Controller.
> [ ---> ]  Disassembling tables...
> [  OK  ]  Disassemble DSDT.
> [  OK  ]  Disassemble FACP.
> [  OK  ]  Search specification tables by syscl/Yating Zhou.
> [ ---> ]  Patching DSDT.dsl
> [  OK  ]  Rename DSM.
> [  OK  ]  Fix word field length Dword->Qword credit syscl.
> [  OK  ]  OS Check Fix.
> [  OK  ]  Fix brightness keys(F11/F12).
> [  OK  ]  HDAS->HDEF.
> [  OK  ]  Add audio Layout 1.
> [  OK  ]  Rename GFX0 to IGPU.
> [  OK  ]  Inject USBX and PNLF credit syscl.
> [  OK  ]  Fix USB _PRW.
> [  OK  ]  IRQ Fix.
> [  OK  ]  SMBus Fix.
> [  OK  ]  AC Adapter Fix.
> [  OK  ]  Add MCHC.
> [  OK  ]  Fix _WAK Arg0 v2.
> [  OK  ]  Add IMEI.
> [  OK  ]  Fix Non-zero Mutex.
> [  OK  ]  Fix MDBG Error credit x4080, syscl.
> [  OK  ]  PPMC and PMCR combine together credit syscl.
> [  OK  ]  Insert DMAC(PNP0200).
> [  OK  ]  Make Device(MATH) load correctly in macOS.
> [  OK  ]  SBTN->SLPB with correct _STA 0x0B.
> [  OK  ]  iGPU TPMX to MEM2.
> [  OK  ]  IMTR->TIMR, _T_x->T_x.
> [  OK  ]  PXSX2ARPT with _PWR fix.
> [  OK  ]  Remove WMI(PNP0C14).
> [  OK  ]  Inject SSD device property credit syscl.
> [  OK  ]  Declare GTF0 method object credit syscl.
> [  OK  ]  Inject NVMe power management properties credit Pike R. Alpha, syscl.
> [  OK  ]  Remove _PWR, _PSW in PWRB(PNP0C0C).
> [  OK  ]  Inject reg-ltrovr for IOPCIFamily::setLatencyTolerance setting ltrOffset for PCI devices successfully (c) syscl.
> [  OK  ]  Fix shutdown become reboot issue.
> [  OK  ]  Remove DSDT backup.
> [ ---> ]  Patching SSDT-14.dsl
> [  OK  ]  Rename DSM.
> [  OK  ]  Rename GFX0 to IGPU.
> [ ---> ]  Patching SSDT-5.dsl
> [  OK  ]  Rename GFX0 to IGPU.
> [  OK  ]  Rename DSM.
> [  OK  ]  Fix PARSEOP_IF error credit syscl.
> [ ---> ]  Fixing reboot issue
> [  OK  ]  Fix reboot issue credit syscl.
> [ ---> ]  Copying tables to precompile...
> [  OK  ]  Copy tables to precompile.
> [ ---> ]  Copying untouched tables to ./DSDT/compile...
> [  OK  ]  Copy untouched tables to ./DSDT/compile.
> [ ---> ]  Compiling tables...
> [  OK  ]  Compiling DSDT.
> [  OK  ]  Compile DptfTa.
> [  OK  ]  Compile SaSsdt.
> [  OK  ]  Compile sensrhub.
> [ ---> ]  Copying SSDT-rmne.aml to ./DSDT/compile...
> [  OK  ]  Copy SSDT-rmne.aml to ./DSDT/compile.
> [FAILED]  Generate C-States and P-State for Intel i7-6600U.
> cp: /Users/mirco/Desktop/Hackintosh/XPS9350-macOS-master/DSDT/prepare/CpuPm-i7-6600U.aml: No such file or directory
> [ ---> ]  Installing SSDT-XPS13SKL.aml to ./DSDT/compile...
> [  OK  ]  Copy SSDT-XPS13SKL.aml to ./DSDT/compile.
> [  OK  ]  Clean dynamic SSDTs.
> [  OK  ]  Drop SSDT-3.
> [  OK  ]  Drop SSDT-6.
> [  OK  ]  Create /Volumes/EFI/EFI/CLOVER/ACPI/patched.
> [  OK  ]  Copy tables to /Volumes/EFI/EFI/CLOVER/ACPI/patched.
> [ ---> ]  Updating kexts...
> [  OK  ]  Remove pervious kexts in /Volumes/EFI/EFI/CLOVER/kexts/10.12.
> [  OK  ]  Update kexts from ./CLOVER/kexts/10.12.
> [  OK  ]  Update kexts from ./Kexts.
> [  OK  ]  Install VoodooPS2Controller.
> [  OK  ]  Remove /Volumes/EFI/EFI/CLOVER/kexts/10.12/BrcmPatchRAM2.kext.
> [  OK  ]  Remove /System/Library/Extensions/BrcmFirmwareRepo.kext.
> [  OK  ]  Remove /System/Library/Extensions/BrcmPatchRAM2.kext.
> [  OK  ]  Install BrcmPatchRAM2.
> [  OK  ]  Install BrcmFirmwareRepo.
> [ ---> ]  Installing audio...
> [  OK  ]  Install audio.
> [ ---> ]  Unlocking maximum pixel clock...
> [  OK  ]  Patch and sign framework.
> [  OK  ]  Generate configuration file of sleepwatcher launch daemon.
> [  OK  ]  Generating script to unmount external devices before sleep (c) syscl/lighting/Yating Zhou.
> [  OK  ]  Generate script to load RTWlanUSB upon sleep.
> [ ---> ]  Installing external devices sleep patch...
> [  OK  ]  Install sleepwatcher daemon.
> [  OK  ]  Install configuration of sleepwatcher daemon.
> [  OK  ]  Install sleep script.
> [  OK  ]  Install wake script.
> [  OK  ]  Fix the permissions of /etc/sysclusbfix.sleep.
> [  OK  ]  Fix the permissions of /etc/sysclusbfix.wake.
> [  OK  ]  Trigger startup service of syscl.usb.fix.
> [  OK  ]  Clean up.
> [  OK  ]  Mount disk0s3.
> [  OK  ]  Create /Users/mirco/Desktop/Hackintosh/XPS9350-macOS-master/Backups/2017-02-09-h16_51_58.
> [ ---> ]  Convert UDZO(r/o) to UDRW(r/w) ...
> [  OK  ]  Convert UDZO(r/o) to UDRW(r/w).
> [  OK  ]  Attach Recovery HD.
> [  OK  ]  Patch and sign framework for Recovery HD.
> [  OK  ]  Detach mountpoint.
> [ ---> ]  Convert UDRW(r/w) to UDZO(r/o) ...
> [  OK  ]  Convert UDRW(r/w) to UDZO(r/o).
> [ ---> ]  Updating Recovery HD for DELL XPS 13 9350...
> [  OK  ]  Clean redundant dmg files.
> [  OK  ]  Unmount disk0s3.
> [ ---> ]  Rebuilding kernel extensions cache...
> [  OK  ]  Rebuild kernel extensions cache.
> [ Note ]  Congratulations! All operation has been completed.
> [ Note ]  Reboot now. -syscl/lighting/Yating Zhou @PCBeta.

Thank you!

**Comment by syscl** [comment]
Oh @ZombieTheBest 

Thank you for your information, I have released there's i7-6600 in XPS 13(or maybe I made a mistake that I use i7-6500). I will correct it. Thank you.

syscl

**Comment by syscl** [comment]
@ZombieTheBest Try the latest deploy.sh

syscl

**Comment by ZombieTheBest** [comment]
thank you @syscl i'll wait for the fix! I guess i will only get a little poor battery life right?

One more thing: with VoodoPS2 i get a "strange" keyboard layout: ALT key is the "cmd key" (ALT+C is copy, ALT+V is paste) and the Windows key i don't know exactly what it does. Is there any way to correct this and use Windows key as cmd key? :) 

And last thing: My trackpad works with VoodooPS2 (it does not with ApplePS2), but sometimes dragging things (like folder or files in finder) is hard and it's like the trackpad get's both fingers and doesn't ignore the one that's pressing the left touchpad button. Any way to fix (or improve) this too? :)

Thank you again! :D

**Comment by ZombieTheBest** [comment]
oh @syscl that was so fast! gonna try it ASAP!

**Comment by syscl** [comment]
@ZombieTheBest Alt are mapping to Command, because that's the same as MacBook's design. You can take a look at a real MacBookPro's keyboard. That's not a bug.

syscl

**Comment by ZombieTheBest** [comment]
Here's the new output: seem's ok to me! :) 
Anything else I have to do to check that it's working? :) 

```
Mircos-MacBook:XPS9350-macOS-master mirco$ sudo ./Deploy.sh
[ ---> ]  Updating files from https://github.com/syscl/XPS9350-macOS...
fatal: Not a git repository (or any of the parent directories): .git
[ Note ]  Your laptop is non-Iris version(i7-6600U).
[  OK  ]  Pre stage cleanup.
[  OK  ]  Create ./DSDT.
[  OK  ]  Create ./DSDT/prepare.
[  OK  ]  Create ./DSDT/precompile.
[  OK  ]  Create ./DSDT/compile.
/dev/disk0 (internal):
   #:                       TYPE NAME                    SIZE       IDENTIFIER
   0:      GUID_partition_scheme                         256.1 GB   disk0
   1:                        EFI EFI                     209.7 MB   disk0s1
   2:          Apple_CoreStorage MacOS                   255.2 GB   disk0s2
   3:                 Apple_Boot Recovery HD             650.0 MB   disk0s3

/dev/disk1 (internal, virtual):
   #:                       TYPE NAME                    SIZE       IDENTIFIER
   0:                            MacOS                  +254.8 GB   disk1
                                 Logical Volume on disk0s2
                                 C4C4B0F0-A5B7-43D0-AB75-49F2E98A1B23
                                 Unencrypted

Enter EFI's IDENTIFIER, e.g. disk0s1: disk0s1
[  OK  ]  Mount disk0s1.
[  OK  ]  Copy untouch ACPI tables.
Available touchpad kext:

[  1  ] ApplePS2SmartTouchPad
[  2  ] VoodooPS2Controller.kext

Please choose the desired touchpad kext (1 or 2): 2
[ Note ]  Use VoodooPS2Controller.
[ ---> ]  Disassembling tables...
[  OK  ]  Disassemble DSDT.
[  OK  ]  Disassemble FACP.
[  OK  ]  Search specification tables by syscl/Yating Zhou.
[ ---> ]  Patching DSDT.dsl
[  OK  ]  _DSM->XDSM.
[  OK  ]  Fix word field length Dword->Qword credit syscl.
[  OK  ]  OS Check Fix.
[  OK  ]  Fix brightness keys(F11/F12).
[  OK  ]  HDAS->HDEF.
[  OK  ]  Inject Audio Info.
[  OK  ]  Rename GFX0 to IGPU.
[  OK  ]  Inject USBX and PNLF credit syscl.
[  OK  ]  Fix USB _PRW.
[  OK  ]  IRQ Fix.
[  OK  ]  SMBus Fix.
[  OK  ]  AC Adapter Fix.
[  OK  ]  Add MCHC.
[  OK  ]  Fix _WAK Arg0 v2.
[  OK  ]  Add IMEI.
[  OK  ]  Fix Non-zero Mutex.
[  OK  ]  Fix MDBG Error credit x4080, syscl.
[  OK  ]  PPMC and PMCR combine together credit syscl.
[  OK  ]  Insert DMAC(PNP0200).
[  OK  ]  Make Device(MATH) load correctly in macOS.
[  OK  ]  SBTN->SLPB with correct _STA 0x0B.
[  OK  ]  iGPU TPMX to MEM2.
[  OK  ]  IMTR->TIMR, _T_x->T_x.
[  OK  ]  PXSX2ARPT with _PWR fix.
[  OK  ]  Remove WMI(PNP0C14).
[  OK  ]  Inject SSD device property credit syscl.
[  OK  ]  Declare GTF0 method object credit syscl.
[  OK  ]  Inject NVMe power management properties credit Pike R. Alpha, syscl.
[  OK  ]  Remove _PWR, _PSW in PWRB(PNP0C0C).
[  OK  ]  Inject reg-ltrovr for IOPCIFamily::setLatencyTolerance setting ltrOffset for PCI devices successfully (c) syscl.
[  OK  ]  Fix shutdown become reboot issue.
[  OK  ]  Remove DSDT backup.
[ ---> ]  Patching SSDT-14.dsl
[  OK  ]  Rename GFX0 to IGPU.
[ ---> ]  Patching SSDT-5.dsl
[  OK  ]  _DSM->XDSM.
[  OK  ]  Rename GFX0 to IGPU.
[  OK  ]  _DSM->XDSM.
[  OK  ]  Fix PARSEOP_IF error credit syscl.
[ ---> ]  Fixing reboot issue
[  OK  ]  Fix reboot issue credit syscl.
[ ---> ]  Copying tables to precompile...
[  OK  ]  Copy tables to precompile.
[ ---> ]  Copying untouched tables to ./DSDT/compile...
[  OK  ]  Copy untouched tables to ./DSDT/compile.
[ ---> ]  Compiling tables...
[  OK  ]  Compiling DSDT.
[  OK  ]  Compile DptfTa.
[  OK  ]  Compile SaSsdt.
[  OK  ]  Compile sensrhub.
[ ---> ]  Copying SSDT-rmne.aml to ./DSDT/compile...
[  OK  ]  Copy SSDT-rmne.aml to ./DSDT/compile.
[  OK  ]  Generate C-States and P-State for Intel i7-6600U.
[ ---> ]  Installing SSDT-XPS13SKL.aml to ./DSDT/compile...
[  OK  ]  Install SsdtS3 table.
[ ---> ]  Installing SSDT-ARPT-RP05.aml to ./DSDT/compile...
[  OK  ]  Install ARPT table.
[  OK  ]  Clean dynamic SSDTs.
[  OK  ]  Drop SSDT-3.
[  OK  ]  Drop SSDT-6.
[  OK  ]  Create /Volumes/EFI/EFI/CLOVER/ACPI/patched.
[  OK  ]  Copy tables to /Volumes/EFI/EFI/CLOVER/ACPI/patched.
[ ---> ]  Updating kexts...
[  OK  ]  Remove pervious kexts in /Volumes/EFI/EFI/CLOVER/kexts/10.12.
[  OK  ]  Update kexts from ./CLOVER/kexts/10.12.
[  OK  ]  Update kexts from ./Kexts.
[  OK  ]  Install VoodooPS2Controller.
[  OK  ]  Remove /Volumes/EFI/EFI/CLOVER/kexts/10.12/BrcmPatchRAM2.kext.
[  OK  ]  Remove /System/Library/Extensions/BrcmFirmwareRepo.kext.
[  OK  ]  Remove /System/Library/Extensions/BrcmPatchRAM2.kext.
[  OK  ]  Install BrcmPatchRAM2.
[  OK  ]  Install BrcmFirmwareRepo.
[  OK  ]  Update /Volumes/EFI/EFI/CLOVER/drivers64UEFI/FSInject-64.efi.
[  OK  ]  Update /Volumes/EFI/EFI/CLOVER/drivers64UEFI/OsxAptioFix2Drv-64.efi.
[  OK  ]  Update /Volumes/EFI/EFI/CLOVER/drivers64UEFI/OsxFatBinaryDrv-64.efi.
[  OK  ]  Update /Volumes/EFI/EFI/CLOVER/drivers64UEFI/DataHubDxe-64.efi.
[  OK  ]  Update /Volumes/EFI/EFI/CLOVER/tools/Shell64U.efi.
[  OK  ]  Update /Volumes/EFI/EFI/CLOVER/tools/bdmesg.efi.
[  OK  ]  Update /Volumes/EFI/EFI/CLOVER/CLOVERX64.efi.
[ ---> ]  Installing audio...
[  OK  ]  Install audio.
[ ---> ]  Unlocking maximum pixel clock...
[  OK  ]  Patch and sign framework.
[  OK  ]  Generate configuration file of sleepwatcher launch daemon.
[  OK  ]  Generating script to unmount external devices before sleep (c) syscl/lighting/Yating Zhou.
[  OK  ]  Generate script to load RTWlanUSB upon sleep.
[ ---> ]  Installing external devices sleep patch...
[  OK  ]  Install sleepwatcher daemon.
[  OK  ]  Install configuration of sleepwatcher daemon.
[  OK  ]  Install sleep script.
[  OK  ]  Install wake script.
[  OK  ]  Fix the permissions of /etc/sysclusbfix.sleep.
[  OK  ]  Fix the permissions of /etc/sysclusbfix.wake.
[  OK  ]  Trigger startup service of syscl.usb.fix.
[  OK  ]  Clean up.
[  OK  ]  Mount disk0s3.
[  OK  ]  Create /tmp/RecoveryHD.
[  OK  ]  Create /Users/mirco/Desktop/Hackintosh/XPS9350-macOS-master/Backups/2017-02-09-h17_07_29.
[ ---> ]  Convert UDZO(r/o) to UDRW(r/w) ...
[  OK  ]  Convert UDZO(r/o) to UDRW(r/w).
[  OK  ]  Attach Recovery HD.
[  OK  ]  Patch and sign framework for Recovery HD.
[  OK  ]  Detach mountpoint.
[ ---> ]  Convert UDRW(r/w) to UDZO(r/o) ...
[  OK  ]  Convert UDRW(r/w) to UDZO(r/o).
[ ---> ]  Updating Recovery HD for DELL XPS 13 9350...
[  OK  ]  Clean redundant dmg files.
[  OK  ]  Unmount disk0s3.
[ ---> ]  Rebuilding kernel extensions cache...
[  OK  ]  Rebuild kernel extensions cache.
[ Note ]  Congratulations! All operation has been completed.
[ Note ]  Reboot now. -syscl/lighting/Yating Zhou @PCBeta.
```

**Comment by syscl** [comment]
For me, it's OK.

syscl

**Comment by ZombieTheBest** [comment]
Yes i think that it is working! I had to disable HWP in Clover to make frequency go lower. Now CPU it's using about 1/1.5W in IDLE according to Intel Power Gadget, with about -950mA / -1000mA in battery usage. Is that good? 👍

**Comment by syscl** [comment]
How about the time remaining in ```Activity Monitor```->```Energy``` ?

syscl

**Comment by ZombieTheBest** [comment]
72% --> 5:55

**Comment by ZombieTheBest** [comment]
now 4:39, Chrome is the only app running, flagged s "hight energy impact"

**Comment by syscl** [comment]
Good battery life, wish my laptop can reach that long. But you know, I have Iris 540 such that my battery life will be 1hour shorter than yours. 

Anyway, good enough.

syscl

**Comment by ZombieTheBest** [comment]
Okay nice thank you! Yeah now it is back to 5:30, so i think that was just Chrome. It's almost the same i got on windows so... Good Job! 👍

**Comment by syscl** [comment]
Use Safari. Chrome will drain a lot of power in my opinion.

syscl

**Comment by ZombieTheBest** [comment]
I will @syscl ! The only thing I like about Chrome are extensions, but on my laptop I think I can live without them! :) 
Btw I'm still using a USB Wifi dongle (waiting for the new internal Wifi Card), and it's a pain in the a** :(

**Comment by ZombieTheBest** [comment]
Oh, sorry just another question! @syscl 
I get an error while I try to download an App from App Store: "Your computer could not be verified". Also iMessage and FaceTime don't work. Siri works sometimes. I already followed the "iMessage Fix guide", this one: https://www.reddit.com/r/hackintosh/comments/2wohwn/getting_imessage_working_on_10102_generating/?st=iyrwcpl9&sh=6101dc02

But nothing :(

**Comment by syscl** [comment]
@ZombieTheBest 

In ```config.plist```->```SMBIOS```, there's two properties you need to keep in mind:
```
SerialNumber
BoardSerialNumber
```

If one of them is missing, you can manually inject in. The information can be found on a real MacBook's ```About This Mac```->```System Report```->```Hardware```, you just take a pic from that tab, then place it in your config.plist, that's it. You can also inject ```Hardware UUID``` from that picture as well.

I have experienced any ban from Apple Store, I use it to buy software, use FaceTime to communicate with my friends and relatives. 

BTW, here's the battery life in class:
![snip20170209_4](https://cloud.githubusercontent.com/assets/11594858/22798679/7d19f740-eec8-11e6-95a7-01ab7ca329a9.png)


syscl

**Comment by ZombieTheBest** [comment]
I just realised my account got black-listed. I will try to call Apple Support to get it white-listed again, hope that it will work! 
And yep, I'm using Safari right now... I think it's even faster than Chrome! 👍

**Comment by syscl** [comment]
@ZombieTheBest Please try latest config.plist with full HWP enable.

syscl

**Comment by ZombieTheBest** [comment]
@syscl Clover can't open your config.plist file. I've checked with notepad and HWP is enabled and SMBios is MacBook Pro 13,2. PM seems to work well (0.8W to 1.3W in IDLE), but of course I still can't download apps from App Store, I guess I need to find a real Mac serial? Or there's something else I can do about it?

**Comment by ZombieTheBest** [comment]
With old config.plist **without** HWP:
<img width="361" alt="without_hwp" src="https://cloud.githubusercontent.com/assets/22716366/22818096/9513dd04-ef6b-11e6-9d90-444f3fa6b116.png">

With new config.plist **with** HWP:
<img width="357" alt="with_hwp" src="https://cloud.githubusercontent.com/assets/22716366/22818109/ace9b23c-ef6b-11e6-87ec-5dc590763f4d.png">

**Comment by ZombieTheBest** [comment]
After some tests I think that the HWP one is better and even if the Frequency is over 1.3Ghz it seems to use less Watts during normal usage. Is the frequency ok? 
<img width="361" alt="schermata 2017-02-10 alle 11 32 07" src="https://cloud.githubusercontent.com/assets/22716366/22823589/95023e6e-ef84-11e6-88f5-3e05f2fd8a98.png">

**Comment by syscl** [comment]
Wait for me releasing X86PlatformPlugin_Injector method.

I have 2 dues, 2 midterms this month.

Sorry,
syscl

**Comment by ZombieTheBest** [comment]
Sure, I'll wait! 👍 
It's already good enough as it is right now :)
