### ISSUE TITLE
BCM94352Z patch - minor issue

### ISSUE THREAD

**Issue by jrpvt** [syscl/XPS9350-macOS#57]
First off, your script is amazing.  This is the easiest deployment of macOS that I've ever seen.  Thank you for this masterpiece.

One minor issue.  I've noticed that as soon as the BCM94352Z darkvoid patch is applied (I followed the [closed issue](https://github.com/syscl/XPS9350-macOS/issues/12) on this) the brightness keys stop functioning and the battery indicator seems to change from showing a percentage to an X briefly, then back to the percentage again.  The display also dims, goes bright, then dims again.  This repeats every minute or so.  I disabled the option to slightly dim the display on battery which fixed the dim, bright, dim loop.

Also, if I run the deploy script after applying the darkvoid patch, it results in a panic cpu caller.  I can revert by booting from USB, restoring your original clover folder, re-running the script and then applying the wifi patch.

Any idea as to why the darkvoid patch might interfere with other system functions (or is something else causing this)?

**Comment by syscl** [comment]
@jrpvt Do you enable ALSD->ALS0 patch in config.plist??

Disable that patch!

syscl

**Comment by jrpvt** [comment]
I just disabled it, saved the config and restarted but no change.

**Comment by syscl** [comment]
Weird, try my latest Clover, re dump all ACPI tables. Then use latest deploy.sh.

 Only added darkvoid's wifi patch. See if this work.

syscl

**Comment by jrpvt** [comment]
That did it!  Thanks man!!

**Comment by syscl** [comment]
@jrpvt Nice.

syscl
