### ISSUE TITLE
DisplayLinkDriver.kext is use for multi monitor?

### ISSUE THREAD

**Issue by x4080** [syscl/XPS9350-macOS#6]
DisplayLinkDriver.kext is use for multi monitor?

**Comment by syscl** [comment]
@x4080 maybe, what specs model you have?

syscl

**Comment by x4080** [comment]
No, I mean what do you use DisplayLinkDriver for? Mine is QHD+ Iris 540

**Comment by syscl** [comment]
No, you have i7-6500, thus you have non-iris version.

DisplayLinkDrive is for external USB dock with such function.

syscl

**Comment by x4080** [comment]
OK thanks
