### ISSUE TITLE
BCM94352Z(DW1560) not working

### ISSUE THREAD

**Issue by pepi2810** [syscl/XPS9350-macOS#60]
So I have followed a previous closed issue and I re dumped the ACPI tables and using your newest clover and re doing the deploy.sh.

But my wifi still doesn't work what should i do?

**Comment by syscl** [comment]
Hi search for the patch name fcvo which is for DW1560 on Sierra.

syscl

**Comment by pepi2810** [comment]
@syscl

Thanks I found a tutorial using that patch.

Thanks :D

**Comment by syscl** [comment]
@pepi2810 Tell me if this solve your issue or not?

If yes, please close this issue.

Thank you,
syscl
