### ISSUE TITLE
clover dont show macos boot option

### ISSUE THREAD

**Issue by duaneya** [syscl/XPS9350-macOS#62]
sorry for disturb..
when I finish install and reboot,my clover just show this ..boot macos install form..and windows boot option
![img_0820](https://cloud.githubusercontent.com/assets/12255185/23100902/7d2885da-f6c5-11e6-900b-5016ce7fdc9b.PNG)

**Comment by squash-** [comment]
When you boot macOS from the internal SSD after installing from USB it finishes up the install from the internal SSD. Much like Windows always has copied everything from CD/DVD/USB and then finished the install on the internal HDD/SSD.

**Comment by duaneya** [comment]
so ...what should I do

**Comment by syscl** [comment]
@duaneya seems like you use another way to create USB installer. Just boot to that installer again, then macOS will finish the whole installation progress.

syscl

**Comment by duaneya** [comment]
I boot this and finish again..but clover still have two option..could you give some install guides?

**Comment by furrybanana** [comment]
Hi, @duaneya 

having a 2nd Mac would make this easier

basically the install is:

* download macOS from Apple Store
* create bootable disk with Unibeast (UEFI only and UEFI64Drivers)
https://www.tonymacx86.com/threads/unibeast-install-macos-sierra-on-any-supported-intel-based-pc.200564/
* terminal: git clone https://github.com/syscl/XPS9350-macOS
* copy CLOVER folder from @syscl 's git clone to the usb disk EFI partition
* Enter BIOS Setting on your Dell with F2, make sure it is AHCI, Secure Boot off -> set it to Legacy
* install macOS, setup user and wifi, open terminal, git clone https://github.com/syscl/XPS9350-macOS
* might need to install Xcode stuff prompted 
* in terminal go to folder: cd XPS9350-macOS
* in terminal give file access to active user: chmod +x Deploy.sh

I prefer to dump the ACPI table at this point:

* shutdown device. remove usb with macOS installer
* at clover boot menu select your installed macOS partition with arrow keys and push 'F4' on your keyboard (I always do a 'Fn + F4' too)
* arrow keys -> shutdown device, insert macOS installer usb disk
* boot up device, log in
* open terminal, cd XPS9350-macOS
* run the script: ./Deploy.sh
* select your EFI (e.g. disk0s1)
* select trackpad setting 1 or 2
* Enter password
* reboot.

hope this helped, I tried to keep it short

**Comment by duaneya** [comment]
@furrybanana thx

**Comment by duaneya** [comment]
@furrybanana thanks again！！
