### ISSUE TITLE
Screen brightness keys non functional

### ISSUE THREAD

**Issue by kultigspritzig** [syscl/XPS9350-macOS#65]
Updated to 4bf0ccf22e2046dc8262e7b3d391f5a67c30a75e today and the screen brightness keys are no longer functional.  I think my previous build was f5524408badd24a8c46831878f033f19cecb2e69. 

I am dissecting the issue now to find the culprit.

**Comment by kultigspritzig** [comment]
OK, turns out  it's the 7b42a5fffe2a3348a697a9be2c8112c50c4de7da that's causing this.

**Comment by syscl** [comment]
Hi @kultigspritzig please provide this information after executing 
```sh
uid=10
ioreg -n AppleBacklightDisplay -arxw0>/tmp/syscl.plist
id=`/usr/libexec/PlistBuddy -c "Print :0:DisplayProductID" /tmp/syscl.plist`
id=`printf "F%02dT%04x" $uid $id`
echo $id
```

Thank you,
syscl

**Comment by kultigspritzig** [comment]
It's F10T1421

**Comment by syscl** [comment]
Thank you @kultigspritzig , please try the latest deploy.sh then report!

syscl

**Comment by kultigspritzig** [comment]
Yep, it's fixed.

**Comment by syscl** [comment]
@kultigspritzig BTW, could you please do me a favor? What specs you have? I'm a bit curious why there's more than 3 panels in XPS 13 93x0(Skylake/Kabylake). Usually there's only 2 variants.

Thank you,
syscl

**Comment by kultigspritzig** [comment]
It's 9350, i7-6500U CPU @ 2.50GHz, 16GB, 512GB SSD. Let me know if you need anything specific?

**Comment by syscl** [comment]
QHD panel or FHD?

Thank you,
syscl

**Comment by kultigspritzig** [comment]
QHD.

**Comment by syscl** [comment]
@kultigspritzig Thank you!

Till now, a lot of people report USB-C HDMI issue, but I don't have any HDMI device to test, if you have HDMI device to test please provide some extra information such that I can see what's wrong:
- [ioreg](https://www.tonymacx86.com/threads/guide-how-to-make-a-copy-of-ioreg.58368/) ```without``` HDMI plugin
- [ioreg](https://www.tonymacx86.com/threads/guide-how-to-make-a-copy-of-ioreg.58368/) ```with``` HDMI plugin

Thank you,
syscl

**Comment by kultigspritzig** [comment]
I will do that tomorrow. However, I already reported in another issue that USB-C HDMI actually works for me.

**Comment by syscl** [comment]
Thank you @kultigspritzig , there's a lot messages unrelated to issues, thus I can't follow per issue.

If you find something interesting, don't hesitate to post here :)

Have a nice day,
syscl

**Comment by kultigspritzig** [comment]
@syscl how do you want me to send the ioreg dump files?

**Comment by syscl** [comment]
@kultigspritzig just drag your files in GitHub. Github support this way to upload files.

syscl

**Comment by kultigspritzig** [comment]
Contains three ioreg snapshots:
- with USB C <> HDMI converter connected
- without USB C <> HDMI converter connected 
- with USB C <> HDMI converter connected but with external screen being green. I have this issue randomly. Need to disconnect and reconnect the USB C plug to make it work - sometimes number of times.

[Archive.zip](https://github.com/syscl/XPS9350-macOS/files/812786/Archive.zip)
