### ISSUE TITLE
dmesg flooded with ApplePS2Keyboard debug messages

### ISSUE THREAD

**Issue by kultigspritzig** [syscl/XPS9350-macOS#69]
Can we have release version of VooodooPS2 enabled by default, maybe with an option in the Deploy.sh?

**Comment by bozma88** [comment]
I confirm, the kext is in debug mode.
@syscl, could you please release the source code for your tweaked voodoops2trackpad?
We'd like to peek at your tweaks, as they work very very well.

**Comment by squash-** [comment]
@bozma88 I do believe the source for the included VoodooPS2Controller is on his github

**Comment by bozma88** [comment]
Ping @syscl.

![screen shot 2017-03-09 at 03 28 08](https://cloud.githubusercontent.com/assets/1729715/23733280/732dacc0-0478-11e7-9564-09da4b265b63.png)

Could you also release your source so we can see what improvements you made?
Thank you so much.

**Comment by syscl** [comment]
@bozma88 see [here](https://github.com/syscl/OS-X-Voodoo-PS2-Controller)

syscl

**Comment by bozma88** [comment]
Oh, sorry, I did not notice the previous reply. Time to go sleeping a bit...

**Comment by syscl** [comment]
Hi everyone, give latest VoodooPS2 from my github a try!

Thank you,
syscl
