### ISSUE TITLE
Please clarify specs

### ISSUE THREAD

**Issue by Nomad347** [syscl/XPS9350-macOS#7]
Your patches are really helpful as my system seems to be more stable and some of the bugs (like sound) I had before seem to be gone. Even though I'm not that good in hackintoshing it seems that you have the model with dedicated graphics. There's multiple systems on the market as I'm sure you're aware. Can you please clarify which specs your patches apply too please?

I have the Intel Core i5-6200U. Integrated HD 520 graphics. 8 Gb ram. Patches applied manually are as follow
DSDT Patches:
[syn] Rename _DSM methods to XDSM
[igpu] Rename GFX0 to IGPU
[igpu] Brightness fix
[sys] Fix _WAK Arg0 v2
[sys] Fix Mutex with non-zero SyncLevel
[sys] HPET Fix
[sys] IRQ Fix
[sys] OS Check Fix (Windows 8)
[sys] RTC Fix
[sys] Skylake LPC
[sys] SMBUS Fix
Change _OSI To XOSI
Change HDAS To HDEF
Change HECI To IMEI
syscl_ALSD2ALS0.txt
syscl_DMAC.txt
syscl_iGPU_MEM2.txt
syscl_IMTR2TIMR.txt
syscl_MATH.txt
syscl_PPMCnPMCR.txt
syscl_SLPB.txt
system_OSYS.txt
usb_prw_0x0d_xhc_skl.txt
usb_prw_0x6d_xhc_skl.txt

As mentioned systems seems stable. Can I ask you to clarify the specs, maybe add a quick read that for any patches that are specific? Like syscl_Iris_Pro.txt ?

Really appreciate your work. Keep it up.

**Comment by syscl** [comment]
I have no time to reply details information, but I am working on this project to make it as perfect as I can. If you want to help, please provide your ioreg information(see [this](https://www.tonymacx86.com/threads/guide-how-to-make-a-copy-of-ioreg.58368/))

I am really want to merge both iris model and non-iris model in this project,  thus what you provide will help.

Thanks,
syscl

**Comment by Nomad347** [comment]
XPS 9350 the model with i5-6200U. HD 520 graphics. 4 gb of ram. Non-touch version, 1080p.
[My Macbook.ioreg.zip](https://github.com/syscl/XPS9350-macOS/files/644081/My.Macbook.ioreg.zip)
Ioreg attached

**Comment by applesjgtl** [comment]
What size / type of SSD do you all have? I'm running into trouble with my i5 due to its M.2 but my i7 with a completely different configuration seems fine. I understand that spec disparities may not be something that syscl has time to discuss but perhaps we should start a Google spreadsheet or something with the various models we're discussing - some way to keep track of which 9530s are working and which aren't and which specs each has since they can be customized so widely.

**Comment by applesjgtl** [comment]
I don't have time to do this tonight but if nobody else beats me to the punch maybe I'll put one together tomorrow and post a link for anyone to edit here. I intend to purchase more 9530s with a friend as we really like the laptops and want to make them a viable, stable alternative to the new MacBook Pros, so I imagine that I'll be adding a few more data points myself as we've been purchasing them all refurbished.

**Comment by gctseng** [comment]
Well, since I can't do shit tonight because my XPS exploded:

[Dell XPS 13 Spreadsheeet](https://docs.google.com/spreadsheets/d/1ifemBuAYkUKhUvtJpKiLYpida5GnNlNPWPd5djalGLU/edit?usp=sharing)

**Comment by syscl** [comment]
@gctseng OMG, exploded?!! what's wrong? Are you still OK?

**Comment by gctseng** [comment]
@syscl LOL. Not literally "exploded". [Hardware Failure Screenshots](https://github.com/syscl/XPS9350-macOS/issues/20)

**Comment by syscl** [comment]
@gctseng Wish it could get fixed soon!

syscl
