### ISSUE TITLE
Can't install to M.2 SSD (non NVMe)

### ISSUE THREAD

**Issue by gjabell** [syscl/XPS9350-macOS#76]
I am running the 2016 1080p non-touch version of the XPS, which has a 128gb M.2 SATA SSD (non NVMe). I initially had trouble booting to the installer using your clover files, but was able to fix it with the -no_compat_check boot flag (installer was hanging due to a "version not supported" error), and also by setting the OS version to 10.12.3 (not entirely sure if this was necessary but it seemed to help). Once I fixed the boot issue I was able to get into the installer, but my SSD wouldn't show up in disk utility or terminal (with diskutil list). I suspect it had to do with it being a SATA SSD rather than NVMe, and per the instructions from [this](https://github.com/syscl/XPS9350-macOS/issues/25) issue, I added the SATA-100-series-unsupported.kext and was able to get the SSD to show up in disk utility.
Unfortunately I am now stuck, because the installer won't install to the SSD since it says "macOS sierra is already installed on this mac". I have tried reformating the drive several times both through the command line and in disk utility but it doesn't seem to fix the issue. I found a thread that said the issue might be fixed using a fakecpuid, but none of the ones that I've tried have worked. I'm not sure if the issue is caused by the boot params I used or by using the SATA-100-series-unsupported.kext, but since I don't have an NVMe drive I don't think I can get the system to recognize the drive without it.
Has anyone else had this issue and found a solution to it? I spent a while looking for answers on forums but unfortunately it seems that there aren't a lot of people with the same problem.

**Comment by gjabell** [comment]
Nevermind, tried using a different config.plist and it fixed the issue.

**Comment by syscl** [comment]
@gjabell Hello, could you please provide the correct config.plist such that I can merge it to this project?

Thank you,
syscl

**Comment by gjabell** [comment]
Sure, I ended up using one of Rehabman's configs ([link](https://github.com/RehabMan/OS-X-Clover-Laptop-Config/blob/master/config_HD520_530_540.plist), which allowed me to uninstall without the weird error. I think the issue may have been with the -no_compat_check but I'm not sure. I also still needed to use the SATA-100-series-unsupported.kext for the drive to be recognized, since I am running SATA m.2 instead of NVME.
