### ISSUE TITLE
Installer not booting

### ISSUE THREAD

**Issue by ronangaillard** [syscl/XPS9350-macOS#8]
Here is the output I have while trying to boot the installer using your CLOVER folder : 
![Screenshot]( http://img11.hostingpics.net/pics/854076DSC0111.jpg)

My config : 
- Dell XPS 13 9350
- Intel® CoreTM i7-6560U @ 2.20 GHz
- Intel Iris Graphics 540
- QHD+ screen

**Comment by syscl** [comment]
@ronangaillard Hi, I have 3 exams next week, I will be back to help you in Wednesday.

Keep on following my update,
syscl

**Comment by syscl** [comment]
@ronangaillard Hi, I fixed it, try the laster clover/config.plist in my github

syscl

**Comment by ronangaillard** [comment]
Thanks I am trying this right now !

**Comment by ronangaillard** [comment]
Solved ! Thanks a lot !
