### ISSUE TITLE
Kernel Panic on lastest commit

### ISSUE THREAD

**Issue by supergarbageman** [syscl/XPS9350-macOS#85]
Hi,
After updating to latest commit (from around commit 198) I am getting a kernel panic.

Something to do with IOUSB kext.

**Comment by syscl** [comment]
@supergarbageman Thank you for the feedback, please try to remove ```USB_injector.kext``` under Clover/kexts/10.12 or Clover/kexts/10.11

I will add the fix for latest deploy later.

syscl

**Comment by supergarbageman** [comment]
No USB injector kext in folder.
Photo attached - not good but best I can seem to take.

![img_0748](https://cloud.githubusercontent.com/assets/15069337/24235599/27204254-0ff2-11e7-981f-7f0daaf4ffc2.JPG)

**Comment by squash-** [comment]
@supergarbageman you have to make sure that your config.plist is in line with @syscl's config.plist in the clover folder. I ran into the same issue. I had to add the SSDT-XHC.aml to the SortedOrder list.

**Comment by syscl** [comment]
@supergarbageman Please try this patch:

[config.plist.zip](https://github.com/syscl/XPS9350-macOS/files/865987/config.plist.zip)
 
And tell me if it works, sorry for the inconvenience.

syscl

**Comment by Nomad347** [comment]
I can confirm the issue above. Problem was fixed after manually changing the plist with the one found in the /home/XPS9350-macOS/Clover folder.

**Comment by supergarbageman** [comment]
All sorted. 

Thanks for all the help!

Keep up the good work @syscl

**Comment by syscl** [comment]
Hi @supergarbageman , is the patched config.plist I sent you solve the issue?

Thank you,
syscl

**Comment by supergarbageman** [comment]
@syscl Yeah, the config.plist you provided was the solution.

**Comment by syscl** [comment]
@supergarbageman Thank you!

syscl
