### ISSUE TITLE
i7-7560U Support in X86PlatformPluginInjector

### ISSUE THREAD

**Issue by kiraraso** [syscl/XPS9350-macOS#86]
Hi everyone, I am trying to get PM working properly (especially the iGPU) on my XPS 13 9360 with the new 7560U CPU. I would really appreciate it if you could update the X86PlatformPluginInjector.kext to support my CPU :) Many thanks in advance!

**Comment by syscl** [comment]
@kiraraso Thank you, added, please try the latest update.

syscl

**Comment by kiraraso** [comment]
Thanks so much! It seems to be working good now - the SSDT from ssdtPRgen used to cause KP on boot but now it's fine and I can see X86PlatformPlugin in IOReg.

The initial problem I had though was with the iGPU, where it seemed to be stuck in the lowest P-state (18) all the time. But now that's fixed with this weird parameter adjustment I found: https://www.tonymacx86.com/threads/guide-dell-xps-13-9360-on-macos-sierra-10-12-x-lts-long-term-support-guide.213141/page-56#post-1463224
I'm not sure if it also applies to 6560Us, but if it does, you can get a nice GPU performance gain :)
