### ISSUE TITLE
Is the default wifi card supported?

### ISSUE THREAD

**Issue by Eduardoveras** [syscl/XPS9350-macOS#87]
Is the default wifi card supported or do you have to phisically change it? not getting wifi signal after a clean install, everything else seems working

**Comment by squash-** [comment]
The DW1820A is not supported. You have to either replace it with a DW1560 or a DW1830

**Comment by syscl** [comment]
@Eduardoveras94 DW1820 may need additional patch similar as fcvo, but I'm sorry that I am lack of time to explore in this area thus I swap my card from DW1820 to DW1830.

syscl
