### ISSUE TITLE
10.12.4 safe to update?

### ISSUE THREAD

**Issue by x4080** [syscl/XPS9350-macOS#88]
Anyone tried?

Thanks

**Comment by furrybanana** [comment]
Yes I am on 10.12.4 with the latest deploy. Everything working except the wifi after standby is bugged/ slow.

**Comment by flipphos** [comment]
Which wifi card are you using? DW 1560 or 1830?

I also upgraded to 10.12.4, so far so good. Haven’t tested my wifi after standby yet. I am using DW 1560.

I found my bluetooth was a bit buggy. I had to have a fresh start to pair my mouse, MX Anywhere 2.

**Comment by furrybanana** [comment]
Bluetooth was working for me after the Update was done and I shutdown the whole system. The first reboot I had no working bluetooth either.

**Comment by x4080** [comment]
Thanks for the info

**Comment by x4080** [comment]
Hi, it seems I cannot boot into Mac after installing update and computer restarted

Is it because of the clover version ? Mine is still 3911

**Comment by furrybanana** [comment]
@x4080 it seems to be so, yes. usually the latest deploy should have updated your clover to r4035

https://www.tonymacx86.com/threads/updated-clover-required-for-kext-injection-in-macos-10-12-4.218062/

**Comment by x4080** [comment]
Thanks I'll try it

**Comment by syscl** [comment]
It's safe, I've updated directly from App Store without even executing deploy..

syscl

**Comment by x4080** [comment]
I got black screen with clover 3911, and now try to fix it using mac installer boot disk :
- backup the clover folder from the boot disk first
- using another mac, I update clover boot disk to newest version 4049 
- and it cant even boot from dell
- change back the clover folder and it can boot from 3911 (but still no lock booting mac os)

Is your repo already use newest clover? I'll try using yours

**Comment by x4080** [comment]
Ok here's what I did :
- Using windows 10, mount the efi, copy the new clover to a new folder in the efi
- Copy all the needed files from old clover
- In the BIOS, add new boot option to this new clover
- Boot it
- Works

Question : the brightness control seems to not working now, hotkey still works but brightness is not changes (always 100%) I think

Anybody has solution?

Thanks

**Comment by x4080** [comment]
Another side question, it seems that in the BIOS, I cannot see the flashdisk partition to add EFI boot to the boot sequence (the old saved EFI flashdisk boot option still there, but cant add new)

Using the latest BIOS I think

Anybody has solution? Thanks

**Comment by syscl** [comment]
@x4080 Please give the latest Clover a try.

syscl

**Comment by x4080** [comment]
Yes, already use latest clover, already boot into mac but the brightness control still not working, you dont have this problem?

Thankfully its not 100% brightness so right now its not a big deal :)

**Comment by x4080** [comment]
Hmm, it seems I still using IntelBacklight.kext in the clover, but yours is using Applebacklightinjector.kext maybe this is why?

**Comment by syscl** [comment]
@x4080 IntelBacklight is useless, and will bite your brightness function on 10.12.4. That's why from 10.12.3 I've created injector method, and this will enable native brightness function on all macOS.

Here's the proof:
![snip20170402_3](https://cloud.githubusercontent.com/assets/11594858/24584939/5c3d0ac2-1744-11e7-944d-16f4781d9b52.png)


syscl

**Comment by x4080** [comment]
Yes, already replaced with your Applebacklightinjector.kext and brightness is not changing, the control shown but no brightness changes 

Should I put it in the S/L/E instead in clover/kexts ?

**Comment by syscl** [comment]
Hi @x4080  please provide this information after executing

```sh
uid=10
ioreg -n AppleBacklightDisplay -arxw0>/tmp/syscl.plist
id=`/usr/libexec/PlistBuddy -c "Print :0:DisplayProductID" /tmp/syscl.plist`
id=`printf "F%02dT%04x" $uid $id`
echo $id
```

Thank you,
syscl

**Comment by x4080** [comment]
Here you go, thanks for helping me

```
Last login: Mon Apr  3 14:04:20 on console
zros-MacBook:~ zro$ uid=10
zros-MacBook:~ zro$ ioreg -n AppleBacklightDisplay -arxw0>/tmp/syscl.plist
zros-MacBook:~ zro$ id=`/usr/libexec/PlistBuddy -c "Print :0:DisplayProductID" /tmp/syscl.plist`
zros-MacBook:~ zro$ id=`printf "F%02dT%04x" $uid $id`
zros-MacBook:~ zro$ echo $id
F10T1421
```

**Comment by syscl** [comment]
@x4080 Weird, pay attention here:

![snip20170403_3](https://cloud.githubusercontent.com/assets/11594858/24598754/bd509332-1812-11e7-8988-5418317bda43.png)

Could you mind provide me another information:
```sh
kextstat |grep -i IntelBa
```

syscl

**Comment by x4080** [comment]
Sure 

```
Last login: Mon Apr  3 14:27:06 on ttys000
zros-MacBook:~ zro$ kextstat |grep -i IntelBa
   40    0 0xffffff7f838e2000 0x5000     0x5000     com.rehabman.driver.IntelBacklight (1.0.10) ECFD8C5E-EADB-3B90-8AB6-EAAFAF62F499 <27 12 11 4 3>
zros-MacBook:~ zro$ 

```

**Comment by syscl** [comment]
@x4080 Now you know why brightness change does not work on your laptop, IntelBacklight.kext bite your brightness change function, remove it, then place my ```AppleBacklightInjector.kext``` under Clover/kexts/10.12, that's it.

syscl

**Comment by bozma88** [comment]
@syscl, have a read here please: https://www.tonymacx86.com/threads/guide-dell-xps-13-9360-on-macos-sierra-10-12-x-lts-long-term-support-guide.213141/page-60#post-1467247

Rehabman explains that the frequencydivider (PWMMax) may be different when cold booting and waking from sleep. When you built that injector, did you verify the BIOS init value of PWMMax?
I ask this because Rehabmans tells me that usually a complex ACPI PNLF patch is needed in order to make vanilla AppleBacklight operate correctly. Did you verify that the BIOS sets the correct PWMMax value upon cold boot?

Thank you.

**Comment by syscl** [comment]
Hi @bozma88 , I cannot open tonymacx86 for such a long time. 

If you prefer native way to power up brightness, then injector method is the way. IntelBacklight will bite your brightness change. IntelBacklight has smooth transition, but I don't know what this is and don't see any benefits on it.

syscl

**Comment by x4080** [comment]
Hi, I understand but what my condition now is (before you asked the oreg -n AppleBacklightDisplay -arxw0>/tmp/syscl.plist)   : I already removed the intelBacklight and put the AppleBackLightInjector in the clover

So my conclusion is somehow the intelBacklight is still active and AppleBackLightInjector is not working

I deleted the IntelBacklight in clover, maybe its till in S/L/E, I'll take a look later, is this conclusion correct ?

Thanks

**Comment by syscl** [comment]
@x4080 Another place to check is /Library/Extensions.

And you can check it through System Report->Extensions->IntelBacklight, it will give you the path.

As a side note, please, ```DO NOT``` mix deploy.sh with any other guides together. I won't give any assistance later on if people do not use guide from my GitHub with deploy. Basically, none of the guide of XPS 13/15 meet the requirement as this project. 

syscl

**Comment by x4080** [comment]
Thanks, no I'm using your deploy.sh, maybe its from the old configuration that I don't delete or somehow I restore it after problem with 10.12.4, because it happened just after 10.12.4 update

**Comment by syscl** [comment]
But, IntelBacklight.kext install in Clover/kexts/10.12, each time deploy.sh get called, kexts/10.12's kext will be removed then copy latest kext to kexts/10.12. 

Please, try to find out where IntelBacklight install in.

Feedback here,
syscl

**Comment by x4080** [comment]
Yes, its quite strange now : 
- In kexts, no intelbacklight
- In S/L/E, no intelbacklight
- In L/E,  no intelbacklight

**Comment by syscl** [comment]
@x4080 Please give me the following:

```sh
kextstat |grep -i IntelBa
ls -l /S*/L*/E* |grep -i 'IntelBa'
ls -l L*/E* |grep -i 'IntelBa'
```

Try to rebuild kernel cache by the following:
```sh
sudo kextcache -i/
```

syscl

**Comment by flipphos** [comment]
Perhapd you can try to rebuild your cache to remove it from your kext cache? Just my guess.

**Comment by x4080** [comment]
@flipphos Thanks, I'll try it

**Comment by x4080** [comment]
@flipphos @syscl Thanks for your help, and it solved now with running kext utility and wait till it finishes

I'll close it now since it's not related to 10.12.4, but need to update the clover as stated above

Hope it will help someone

**Comment by syscl** [comment]
@x4080 Actually, if you have some problem/issues after update, you can just re run deploy then reboot. It will do all the work for you(including rebuild kernel cache). It's just a simply ./deploy.sh

syscl

**Comment by syscl** [comment]
Kext utility will touched your system's kext, e.g. msdosfs.kext and another one related to blacklist. 

So, why not use deploy.sh to fix all issues? More clean and fast. 

syscl

**Comment by x4080** [comment]
Yes, I use different keyboard, and still have original wifi card and don't remember what else that's different
