### ISSUE TITLE
CLOVER no longer saves ACPI tables?

### ISSUE THREAD

**Issue by kultigspritzig** [syscl/XPS9350-macOS#91]
I upgraded BIOS today to 1.4.14 and wanted to regenerate ACPI patches, but no matter what I do, I can't get CLOVER to save ACPI tables. Trying F4, Fn-F4, etc. - nothing. Can anyone confirm?

I was able to save screenshots and preboot.log, so it's nothing to do with partitioning.

PS. Preboot.log says:
49:377  0:000  Saving ACPI tables from RSDP 79152000 to EFI\CLOVER\ACPI\origin ...
49:377  0:000   79152000: 'RSD PTR ', Rev: 2 (Acpi 2.0 or newer), Len: 36
49:377  0:000    (Xsdt: 791520B8, Rsdt: 79152028)
49:377  0:000    791520B8: 'XSDT', 'CBX3   ', Rev: 1, Len: 236 -> XSDT.aml - Not Found
49:382  0:005    79152028: 'RSDT', 'CBX3   ', Rev: 1, Len: 136 -> RSDT.aml - Not Found
49:387  0:005   No Rsdt and Xsdt - exiting.
(...)
49:761  0:005  Saving DSDT to EFI\CLOVER\ACPI\origin\DSDT-10000000.aml failed - Not Found
(...)
83:757  0:000  Saving ACPI tables from RSDP 79152000 to EFI\CLOVER\ACPI\origin ...
83:757  0:000   79152000: 'RSD PTR ', Rev: 2 (Acpi 2.0 or newer), Len: 36
83:757  0:000    (Xsdt: 791520B8, Rsdt: 79152028)
83:757  0:000    791520B8: 'XSDT', 'CBX3   ', Rev: 1, Len: 236
83:757  0:000    79152028: 'RSDT', 'CBX3   ', Rev: 1, Len: 136
83:757  0:000    Tables in Xsdt: 25
83:757  0:000    0. 79173188: 'FACP', 'CBX3   ', Rev: 5, Len: 268 -> FACP.aml - Not Found

**Comment by kultigspritzig** [comment]
Eventually, after few days, somehow they got generated. Weird.

**Comment by flipphos** [comment]
I also upgraded my 9350's BIOS to 1.14.14 today and had no problem to regenerate ACPI data and ran the deploy.sh smoothly.

Best Regards,
Hong
