### ISSUE TITLE
Kernel panic when booting into installer

### ISSUE THREAD

**Issue by gjabell** [syscl/XPS9350-macOS#92]
Hey everyone,

I am trying to install sierra on my XPS 9350, but I keep getting kernel panics around halfway through booting. I have (as far as I know) correctly created the boot media, replaced the Clover folder, and dumped the ACPI tables. I have attached some pictures of the error messages and screen corruption after the error message. The odd thing is that I was able to successfully install mac os a couple of weeks ago (I uninstalled it because I didn't have a compatible wireless card, but now that I have one I am reinstalling). Does anyone have any ideas what's causing this error? I am booting cold without any extra clover boot flags.

Thanks!

![kernel1](https://cloud.githubusercontent.com/assets/16339512/24785434/d211c1a2-1b27-11e7-853e-64cc4c008b99.jpg)
![kernel2](https://cloud.githubusercontent.com/assets/16339512/24785439/d6305032-1b27-11e7-985b-f4407707346d.jpg)

**Comment by furrybanana** [comment]
System specs of the 9350 (WiFi card, CPU, RAM, drive, model no,....)

Did you create the ACPI tables on the USB drive and pasted it to your internal drive's EFI, then run ./deploy.sh ?

Check if you followed this list: https://github.com/syscl/XPS9350-macOS/issues/62#issuecomment-280959860

**Comment by gjabell** [comment]
Hey @furrybanana,

I am running a 2016 13" model, Intel i5-6200U (Skylake), 8gb ram, 256gb NVMe ssd (didn't originally come with the computer, but I bought a used one from another XPS), DW1560 wifi adapter (replaced my 1820A with the 1560, I tried booting without the adapter and it crashed at the same point, so I don't think it's the issue).

I did dump the ACPI tables, but I wasn't able to even get into the mac os installer, so I can't copy them to the internal drive or run deploy. I did use clover instead of unibeast to create the installer, so maybe that's the issue? Although I was able to use clover earlier and boot successfully, so I think it might be an issue with the custom clover files or maybe clover version. I also tried using a previous commit (the last one that I remember working) but that didn't work either.

Thanks!

**Comment by squash-** [comment]
That isn't a kernel panic. That is "Still Waiting for Root Device" error. It's not booting from your flash drive properly for some reason.

**Comment by gjabell** [comment]
@squash- That looks to be the issue; I tried a different usb and used the unibeast installer to create it and was able to get to the installer successfully. I'll post again if I run into any other issues.

Thanks!

**Comment by hebert1410** [comment]
Hi, I know this issue is closed but I am running exactly in the same issue which my computer crashes in the middle of loading the installation boot. I tried verbose mode and have exactly the same pattern. I tried using different USB flash drives, even new ones and so far I can't find any way to make it work. Is there anything else you did differently to make it boot?

**Comment by yasster** [comment]
@hebert1410 Are you installing High Sierra or Sierra?

**Comment by hebert1410** [comment]
I'm installing High Sierra

**Comment by yasster** [comment]
@hebert1410 Could you provide a copy of your USB Clover? I'll take a look at it!

**Comment by hebert1410** [comment]
It is the exact same Clover folder that syscl posted on this Git. The 2018-03-17 release.

**Comment by yasster** [comment]
@hebert1410 Sorry for the late reply, if it is the same;

Make sure to include `Lilu.kext` in the clover folder, I'm assuming it's causing you the kernel panic!

**Comment by hebert1410** [comment]
Tried that and also nothing :(

**Comment by yasster** [comment]
@hebert1410 Have you followed the settings for your BIOS and what is enabled?

**Comment by hebert1410** [comment]
Yes I followed the settings for the BIOS. Secure boot is disabled and the SATA operation is in AHCI. My BIOS version is 1.5.1, will that affect the way it boots the installer? I ran it in verbose and It constantly crashes at "Still waiting for root device" for both Sierra and High Sierra

**Comment by yasster** [comment]
@hebert1410  Try different USB, if your using USB3, try USB2 and plug them in different ports. If you got all the instructions right, then the only issue is that your Unibeast installation could be corrupted or that the USB is not found!

**Comment by hebert1410** [comment]
I tried it with two different USB 2.0 drives and also tried them in every silver port. I tried also installing it through Unibeast and a terminal command multiple times and the result is always the same :(
