### ISSUE TITLE
Use migration Assistant.app migrate to real mac,then no sounds.

### ISSUE THREAD

**Issue by aizigao** [syscl/XPS9350-macOS#98]
In my new company,I just get a new macbookPro 2016, and I use migration Assistant.app migrate to my new mac, but no sounds drive found 
![image](https://cloud.githubusercontent.com/assets/14126445/25622332/a8a56fb2-2f86-11e7-91d9-0c0f0c7d5dd2.png)
![image](https://cloud.githubusercontent.com/assets/14126445/25622344/ad3f12da-2f86-11e7-9f92-c7eb2305b292.png)

**Comment by syscl** [comment]
please remove AppleHDA_ALC256.kext under /System/Library/Extensions

**Comment by aizigao** [comment]
Thx, it works now. but which kext is light control, is same problem?
![image](https://cloud.githubusercontent.com/assets/14126445/25644428/72c875e0-2fd8-11e7-8a8d-39a2787d80fe.png)
